#!/usr/bin/env python3
"""A source-scoped connection pass; evaluation and documentary evidence stay distinct."""
from pathlib import Path
import json,re,html,hashlib
from apply_iteration_17 import enc,parse,upsert,source_record,node_record,profile_record,edge_record,relation_record
from apply_iteration_09 import graph_metrics
from apply_relational_depth_16 import calculate_relational_depth,write_relational_document
from apply_doncaster_lineage import refresh_counts
from refresh_graph_snapshot import calculate,write
ROOT=Path(__file__).resolve().parents[1]
DATE='2026-09-09'
MARK='september_connections_2026'
BASE=json.loads((ROOT/'sources/september-2026/base-records.json').read_text())
def slug(x):return re.sub('[^a-z0-9]+','_',x.lower()).strip('_')
def source(d,key,title,url,notes,creators=(),publisher='',kind='primary_public_webpage'):
    s=source_record(key,title,kind,url,notes,list(creators),publisher,DATE,quality='B' if kind=='submitted_reading_recommendation' else 'A')
    s.update(last_checked=DATE,review_status='source_scope_checked',connection_pass=MARK);upsert(d['sources'],[s],'id');return key

def node(d,key,title,kind,summary,sids,tags=(),aliases=()):
    matches=[n for n in d['nodes'] if n['entity_type']==kind and (n['id']==key or n['label'].casefold()==title.casefold() or title.casefold() in [str(a).casefold() for a in parse(n.get('aliases'))])]
    if matches:
        key=d.get('canonical_redirects',{}).get(matches[0]['id'],matches[0]['id']);n=next(n for n in d['nodes'] if n['id']==key)
        if not any(x['id']==key for x in BASE['nodes']):BASE['nodes'].append(json.loads(json.dumps(n)))
        n['source_ids']=enc(list(dict.fromkeys(parse(n.get('source_ids'))+sids)));n['aliases']=enc(list(dict.fromkeys(parse(n.get('aliases'))+list(aliases))))
    else:
        v=int(hashlib.sha256(key.encode()).hexdigest()[:8],16)
        n=node_record(key,title,kind,summary,sids,(v%1000)/1000-.5,((v//1000)%1000)/1000-.5,list(tags),aliases=list(aliases),level='described')
        n.update(inclusion_reason=MARK,status='candidate',review_status='source_scoped_research_pass',reviewed_by='',reviewed_at='',set_tags=enc(list(tags)+[MARK]));d['nodes'].append(n)
    return key

def edge(d,a,b,typ,family,phrase,sids,locator,scope,mode='asserted'):
    if a==b:return
    key='e24_'+slug(a+'_'+typ+'_'+b)
    if any(e['source']==a and e['target']==b and e['relation_type']==typ and not e['id'].startswith('e24_') for e in d['edges']):return
    e=edge_record(key,a,b,typ,family,phrase,sids,locator,scope,status='candidate',mode=mode,confidence='',review_label='Located source statement; independent review not recorded' if mode=='asserted' else 'Editorial comparison; open to challenge')
    e.update(reviewed_by='',reviewed_at='');upsert(d['edges'],[e],'id')

def profile(d,nid,summary,why,distinctions,practices,sids,locator,limits):
    previous=next((p for p in d['profiles'] if p['node_id']==nid),None)
    if previous and not any(p['node_id']==nid for p in BASE['profiles']) and nid not in BASE.get('absent_profiles',[]):BASE['profiles'].append(json.loads(json.dumps(previous)))
    if not previous and nid not in BASE.setdefault('absent_profiles',[]):BASE['absent_profiles'].append(nid)
    p=profile_record(nid,summary,why,distinctions,[],[],[],practices,[],limits,sids,context=locator,editorial_note='Prepared with AI assistance from the specified sources. Publication is authorised; independent specialist review is not recorded. Practice implications are editorial applications.')
    p.update(title=next(n['label'] for n in d['nodes'] if n['id']==nid),last_researched=DATE,profile_status='source_scoped_research_pass',review_status='independent_review_not_recorded',reviewed_by='',reviewed_at='')
    upsert(d['profiles'],[p],'node_id');n=next(n for n in d['nodes'] if n['id']==nid);n.update(publication_level='profile',description=summary,canonical_definition=summary,public_stub_text='')

def page(path,title,body):
    p=ROOT/'docs'/path/'index.html';p.parent.mkdir(parents=True,exist_ok=True)
    p.write_text('<!doctype html><html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+html.escape(title)+' | The Necessary Tangle</title><link rel="canonical" href="https://transduction.systems/'+path+'/"><style>body{font:18px/1.65 system-ui;color:#19272d;max-width:980px;margin:auto;padding:24px;background:#faf9f5}h1{line-height:1.15}a{color:#145d69;overflow-wrap:anywhere}table{border-collapse:collapse;width:100%}th,td{text-align:left;vertical-align:top;border-bottom:1px solid #ccd5d8;padding:.7em}td:first-child{min-width:120px}nav{display:flex;gap:1em;flex-wrap:wrap}.note{padding:1em;background:#edf1ee} @media(max-width:650px){table,tbody,tr,td{display:block}thead{display:none}td{padding:.5em}}</style></head><body><nav><a href="/">Atlas</a><a href="/reading-list.html">Reading</a><a href="/systems-thinking/practice/">Practice</a><a href="/events/">Events</a><a href="/updates/">Updates</a></nav><main><h1>'+html.escape(title)+'</h1>'+body+'</main></body></html>\n')

def main():
    d=json.loads((ROOT/'data/public-data.json').read_text())
    for typ,family,phrase in [('offers_reading_route_to','documentary','offers a reading route to'),('implements_notation_for','practical','implements a notation for'),('depicts_coordination_in','conceptual','depicts coordination in'),('depicts_recursive_units_in','conceptual','depicts recursive units in'),('helps_identify','practical','helps identify'),('applies_principle','conceptual','applies the principle'),('introduces_distinction','conceptual','introduces the distinction'),('requires_authority_for','conceptual','requires authority for'),('compares_method','conceptual','compares the method'),('authored_by','documentary','is authored by'),('edited_by','documentary','is edited by'),('presents_account_of','conceptual','presents an account of'),('distinguishes_from','conceptual','distinguishes from')]:
        if not any(r['relation_type']==typ for r in d['relation_types']):upsert(d['relation_types'],[relation_record(typ,family,'inverse_'+typ,'A specified source passage or explicitly labelled editorial comparison',phrase)],'relation_type')
    rec=source(d,'src_ing_ocad_reading_recommendations_2026','David Ing: core readings for Understanding Systems','https://github.com/antlerboy/the-necessary-tangle/issues/2#issuecomment-5558769097','Publicly supplied reading recommendation, including the six core resources and the separate roles of instructor Stephen N. Davies and volunteer David Ing. This supports recommendation and role attribution, not a complete reading of the course.',['David Ing'],'The Necessary Tangle public intake','submitted_reading_recommendation')
    ocad=source(d,'src_ocad_sfin6011_pro_forma_2026','Understanding Systems: SFIN-6011 winter 2026 pro forma','https://coevolving.com/ocadu/202601-sfin-6011/pro-forma/Whole_2026_SFIN6011_pro-forma_v0101a.html','Primary course source supplied for close reading. Retrieval was unavailable on 9 September. No module-by-module contents or influence claims have been inferred.',['David Ing'],'Coevolving','course_source_pending_retrieval')
    route=node(d,'corpus_ing_ocad_reading_route_2026','Understanding Systems: Ing’s OCAD reading route','corpus','A guided entrance to the six resources identified in David Ing’s recommendation for the winter 2026 OCAD course. The complete 13-week pro forma remains a separate source-reading task.',[rec,ocad],['education','systems'])
    sources=[];works=[]
    bibli=[
      ('coping_complexity','Tools, Exercises, and Strategies for Coping With Complexity','https://www.igi-global.com/book/tools-exercises-strategies-coping-complexity/302472','R. Storesund; Ian I. Mitroff','IGI Global','Publication metadata and the submitted reading recommendation checked; full text not reviewed.','publication'),
      ('systems_thinker_archive','The Systems Thinker','https://thesystemsthinker.com/about/','The Systems Thinker','Leverage Networks','Publisher’s About page and the submitted reading recommendation. An archive of multiple authors, not one authored theory.','corpus'),
      ('systems_approaches_change_2020','Systems Approaches to Making Change: A Practical Guide','https://link.springer.com/book/10.1007/978-1-4471-7472-1','Martin Reynolds; Sue Holwell','Springer','Second edition, 2020. Publisher metadata checked; the introductory chapter abstract provides a bounded comparison of five methods.','publication'),
      ('systems_thinkers_ramage_shipp','Systems Thinkers','https://link.springer.com/book/10.1007/978-1-4471-7475-2','Magnus Ramage; Karen Shipp','Springer','Second edition, 2020. Ramage and Shipp are credited by the publisher as authors.','publication'),
      ('contexts_journal','Contexts: The Systemic Design Journal','https://systemic-design.org/contexts/','Systemic Design Association','Systemic Design Association','Journal named in the submitted recommendation. Article-level review remains open.','corpus'),
      ('she_ji_journal','She Ji: The Journal of Design, Economics, and Innovation','https://www.sciencedirect.com/journal/she-ji-the-journal-of-design-economics-and-innovation','Tongji University','Tongji University / Elsevier','Journal named in the submitted recommendation. Article-level review remains open.','corpus')]
    for key,title,url,creators,publisher,notes,kind in bibli:
        sid=source(d,'src_sep_'+key,title,url,notes,creators.split('; '),publisher,'publisher_record' if 'springer' in url or 'igi-' in url else 'resource_metadata')
        nid=node(d,('publication_' if kind=='publication' else 'corpus_')+key,title,kind,notes,[sid,rec],['reading','systems']);works.append(nid);sources.append(sid)
        edge(d,route,nid,'offers_reading_route_to','documentary','offers a reading route to',[rec],'Six-item core reading recommendation','Selection for teaching. No intellectual influence, equivalence, or approval of every claim is inferred.')
    for nid,people,sid,typ in [(works[0],[('person_r_storesund','R. Storesund'),('person_ian_i_mitroff','Ian I. Mitroff')],sources[0],'authored_by'),(works[2],[('person_martin_reynolds','Martin Reynolds'),('person_sue_holwell','Sue Holwell')],sources[2],'edited_by'),(works[3],[('person_magnus_ramage','Magnus Ramage'),('person_karen_shipp','Karen Shipp')],sources[3],'authored_by')]:
        for key,label in people:
            person=node(d,key,label,'person','Credited '+('editor' if typ=='edited_by' else 'author')+' of '+next(n['label'] for n in d['nodes'] if n['id']==nid)+'.',[sid],['systems','writing'])
            edge(d,nid,person,typ,'documentary','is edited by' if typ=='edited_by' else 'is authored by',[sid],'Publisher author/editor metadata','Bibliographic credit only.')
    chapter=source(d,'src_reynolds_holwell_intro_2020','Introducing Systems Approaches','https://link.springer.com/chapter/10.1007/978-1-4471-7472-1_1','Abstract and publisher bibliographic record inspected. Full chapter is subscription content and was not reviewed.',['Martin Reynolds','Sue Holwell'],'Springer','primary_chapter_abstract')
    intro=node(d,'publication_reynolds_holwell_intro_2020','Introducing Systems Approaches (2020)','publication','The introductory chapter compares SD, VSM, SODA, SSM and CSH through their use in situations of change, constructivist potential and adaptability in combinations.',[chapter],['methodology'])
    for suffix in ['system_dynamics','viable_system_model_vsm','strategic_options_development_and_analysis_soda','soft_systems_methodology_ssm','critical_systems_heuristics_csh']:
        edge(d,intro,'method_or_methodology_'+suffix,'compares_method','conceptual','compares the method',[chapter],'Chapter abstract, pp. 1–24 record','The abstract supports the authors’ stated comparative rationale. It does not establish that the methods are interchangeable or that the whole chapter was read.')
    edge(d,works[2],intro,'offers_reading_route_to','documentary','offers a reading route to',[chapter],'Book title and chapter record','Part-to-whole reading route only.')
    # FEM: scope each statement to the author’s explicit use, rather than making VSM a synonym for FEM.
    femid='intervention_skill_fractal_enterprise_model_and_capabilities'
    fs=source(d,'src_fem_toolkit_2026','FEM toolkit 1.3','https://fractalmodel.blogs.dsv.su.se/fem-toolkit/','Official toolkit page inspected. It lists Windows, Linux and Mac installers and explains the Windows code and virtualisation. Installer availability is not a platform compatibility test.',['Fractal Enterprise Model project'],'Stockholm University project site')
    f2=source(d,'src_fem_vsm_system2','System 2 of VSM through the lens of FEM','https://fractalmodel.blogs.dsv.su.se/vsms2fem/','Inspected the explanatory text: FEM patterns depict coordination needs and possible System 2 arrangements. The project’s criticism of VSM visual notation is its own assessment.',['Fractal Enterprise Model project'],'Stockholm University project site')
    f1=source(d,'src_fem_vsm_system1','Decomposition of System 1 units of VSM','https://fractalmodel.blogs.dsv.su.se/vsm-s1-decomposition/','Inspected text on responsibilities, process/asset boundaries, ghosts and groups. Decomposition may denote variants or parts, which must be distinguished.',['Fractal Enterprise Model project'],'Stockholm University project site')
    fc=source(d,'src_fem_structural_coupling','Structural coupling through FEM','https://fractalmodel.blogs.dsv.su.se/structural-coupling-2/','Inspected project account of identifying enterprise-environment couplings. It attributes the term to Maturana and Varela and cites Hoverstadt’s strategy application; those historical claims remain attributed.',['Fractal Enterprise Model project'],'Stockholm University project site')
    toolkit=node(d,'tool_fem_toolkit','FEM toolkit','tool','A diagramming tool for Fractal Enterprise Models. Version 1.3 is listed with three operating-system installers; installation has not been independently tested in this pass.',[fs],['enterprise','modelling'])
    coupling=node(d,'concept_structural_coupling','Structural coupling','concept','Repeated system-environment interaction can shape the structures through which further interaction occurs. The FEM project uses this idea to identify consequential enterprise-environment relationships; that application is narrower than the biological concept.',[fc],['cybernetics'])
    edge(d,toolkit,femid,'implements_notation_for','practical','implements a notation for',[fs],'Toolkit introduction','Tool support; no claim of independent compatibility testing.')
    vsm='method_or_methodology_viable_system_model_vsm'
    edge(d,femid,vsm,'depicts_coordination_in','conceptual','depicts coordination in',[f2],'Opening text and System 2 pattern description','A modelling application to System 2, not a replacement of the entire VSM.')
    edge(d,femid,vsm,'depicts_recursive_units_in','conceptual','depicts recursive units in',[f1],'Responsibility, ghosts and groups paragraphs','System 1 process and asset decomposition; distinctions between parts and variants remain necessary.')
    edge(d,femid,coupling,'helps_identify','practical','helps identify',[fc],'Final explanatory paragraph and higher-education example','The author’s proposed enterprise-modelling use. No proof that every structural coupling will be found.')
    profile(d,femid,'Fractal Enterprise Model connects business processes and the assets they use and maintain. The project shows how its notation can represent VSM coordination, recursive operational units and selected enterprise-environment relationships.','The diagrams offer a way to inspect concrete processes, assets and responsibilities when a generic organisational model is too coarse.',['FEM notation is distinct from the VSM’s account of viability.','Decomposing a model into variants is distinct from decomposing it into parts.','An installer download is distinct from a tested installation.'],['Inspect which processes use or maintain an asset.','Use the System 2 and System 1 examples to question coordination and responsibility.'],[fs,f2,f1,fc],'Official toolkit and three linked application pages.',['Independent validation of the modelling claims remains open.','Platform compatibility has not been tested.'])
    # Taylor and Boxer: a public working paper with versioned, page-specific evidence.
    ps=source(d,'src_taylor_boxer_boundary_2026','What the boundary cannot carry alone, working redraft v3','https://antlerboy.com/library/what-the-boundary-cannot-carry-alone/','Taylor and Boxer, 26 August 2026. All seven pages of the supplied manuscript inspected; not a peer-reviewed final article. The title page gives v3; the running footer retains v1.',['Benjamin P Taylor','Philip Boxer'],'Benjamin P Taylor public work library','working_paper')
    paper=node(d,'publication_boundary_cannot_carry_alone','What the boundary cannot carry alone','publication','Taylor and Boxer’s working paper distinguishes form of response from scope of holding and proposes organisational conditions that can sustain relational public services.',[ps],['public-services','relational'])
    ben=node(d,'person_benjamin_p_taylor','Benjamin P Taylor','person','Systems practitioner and educator, and co-author with Philip Boxer of What the boundary cannot carry alone. This entry starts from inspectable public work and does not claim a complete account of his contributions.',[ps],['public-services','practice'],['Benjamin Taylor','Benjamin P. Taylor','antlerboy'])
    boxer='person_philip_boxer'
    for author in [ben,boxer]:edge(d,paper,author,'authored_by','documentary','is authored by',[ps],'Title page, p. 1','Author order: Benjamin P Taylor, then Philip Boxer.')
    terms=[('form_of_response','Form of response (relational public services)','The paper’s axis for how far a citizen’s situation can reshape an institutional response, from a fixed frame towards a response that can revise the task.'),('scope_of_holding','Scope of holding (relational public services)','The paper’s axis for where sense-making, capability, uncertainty, resources and risk are carried: encounter, service, system conditions, place or citizen association.'),('strategy_ceiling','Strategy ceiling (Taylor and Boxer)','The point above which learning from an encounter cannot alter the rules, resources, measures or institutional choices shaping it.'),('consequential_learning','Consequential learning (relational public services)','Learning that can change the rules, resources, task or boundary of public-service work, instead of remaining a local reflection without an institutional response.')]
    ids=[]
    for key,title,summary in terms:
        nid=node(d,'concept_'+key,title,'concept',summary,[ps],['public-services','relational']);ids.append(nid)
        edge(d,paper,nid,'introduces_distinction','conceptual','introduces the distinction',[ps],'pp. 2–5; Figure 1 and Table 2','A practitioner proposition in this specific working paper, not an independently validated instrument.')
    edge(d,ids[0],ids[1],'distinguishes_from','conceptual','distinguishes from',[ps],'pp. 2–3, Figure 1','Position, health and fit are separate judgements; a wider scope is not automatically better.')
    edge(d,paper,'concept_requisite_variety','applies_principle','conceptual','applies the principle',[ps],'p. 2, paragraph following Table 1','Variety of response relative to demand; the paper also questions whether the task boundary itself is adequate.')
    edge(d,paper,vsm,'applies_principle','conceptual','applies the governance account in',[ps],'p. 5, Governance and consequential learning; Beer 1979 and Espejo/Reyes 2011 references','An application of organisational governance and identity revision; not validation of the whole proposed diagnostic.')
    edge(d,ids[2],ids[3],'requires_authority_for','conceptual','requires authority for',[ps],'p. 4, Strategy ceiling; p. 5, Governance and consequential learning','Crossing the ceiling requires a route by which evidence can change institutional conditions.')
    profile(d,paper,'A relational encounter can improve while the organisation behind it remains unchanged. Taylor and Boxer distinguish form of response, scope of holding, health and fit, then propose four organisational conditions for sustaining relational public services.','It makes the organisational demands behind relational practice explicit, including what evidence must be able to change.',['Form of response differs from scope of holding.','A wider scope is not necessarily healthier or better fitted to demand.','Relational behaviour differs from authority to revise rules and resources.'],['Start with actual demand in citizens’ words.','Ask who carries the work and risk, and what happens to learning.'],[ps],'Working redraft v3, pp. 1–7; Figure 1 and Tables 1–2.',['The authors describe a practitioner proposition, not a validated instrument.','Title-page v3 is retained; the source’s running footer still says v1.'])
    # A bounded pass on new people/organisation submissions, using located primary records.
    hs=source(d,'src_handbook_systems_sciences_2021','Handbook of Systems Sciences','https://link.springer.com/referencework/10.1007/978-981-15-0720-5','Publisher metadata and overview inspected. Editorial credits establish roles in this volume; the whole handbook has not been read.',['Gary S. Metcalf','Kyoichi Kijima','Hiroshi Deguchi'],'Springer','publisher_record')
    handbook=node(d,'publication_handbook_systems_sciences_2021','Handbook of Systems Sciences','publication','The 2021 handbook edited by Metcalf, Kijima and Deguchi presents relationships between systems theories and their use in modelling and practice.',[hs],['systems','reference'])
    for key,label,aliases in [('person_gary_s_metcalf','Gary S. Metcalf',['Gary Metcalf']),('person_kyoichi_kijima','Kyoichi Kijima',['Kyoichi (Jim) Kijima','Jim Kijima']),('person_hiroshi_deguchi','Hiroshi Deguchi',[])]:
        nid=node(d,key,label,'person','Co-editor of the 2021 Handbook of Systems Sciences. This initial entry records the publisher-verified contribution; a fuller intellectual profile remains open.',[hs],['systems'],aliases)
        edge(d,handbook,nid,'edited_by','documentary','is edited by',[hs],'Editors and bibliographic information','Role in this volume; no claim about relative influence or current institutional office.')
    orgs=source(d,'src_ifsr_isss_member_2026','ISSS: IFSR member record','https://ifsr.org/member/international-society-for-the-systems-sciences-isss/','IFSR member page inspected: interdisciplinary inquiry, society name history and practical exchange. Membership supports a specific institutional connection, not consensus across the field.',['IFSR'],'IFSR','institutional_record')
    isss=node(d,'organisation_isss','International Society for the Systems Sciences','organisation','An interdisciplinary systems-sciences society, previously named the Society for General Systems Research. Its IFSR member record describes both theoretical inquiry and exchange among practitioners.',[orgs],['systems'],['ISSS','Society for General Systems Research'])
    ifsr=node(d,'organisation_ifsr','International Federation for Systems Research','organisation','A federation connecting systems-research organisations. The linked member record establishes its relationship with ISSS; broader institutional history remains a separate research task.',[orgs],['systems'],['IFSR'])
    if not any(r['relation_type']=='member_of' for r in d['relation_types']):upsert(d['relation_types'],[relation_record('member_of','institutional','has_member','Institutional member register','is a member of')],'relation_type')
    edge(d,isss,ifsr,'member_of','institutional','is a member of',[orgs],'Member-page heading and Back to Members context','Membership recorded on the IFSR site.')
    ms=source(d,'src_midgley_anu_2026','Gerald Midgley: ANU School of Cybernetics profile','https://cybernetics.anu.edu.au/people/gerald-midgley/','Institutional profile inspected; it records systems intervention work, books, and the 2013/14 ISSS presidency.',['Australian National University'],'ANU','institutional_profile')
    edge(d,'person_gerald_midgley',isss,'held_role_in','institutional','held the 2013/14 presidency of',[ms],'Biographical paragraph: 2013/14 President','Historical role, not a statement about the current presidency.')
    if not any(r['relation_type']=='held_role_in' for r in d['relation_types']):upsert(d['relation_types'],[relation_record('held_role_in','institutional','had_role_holder','Dated institutional biography','held a specified role in')],'relation_type')
    ts=source(d,'src_trist_palgrave_2017','Eric Trist: An American/North American View','https://link.springer.com/referenceworkentry/10.1007/978-3-319-49820-1_27-1','Abstract and bibliographic metadata inspected; full subscription chapter not reviewed. The abstract discusses sociotechnical systems, organisation design, action research and work with Fred Emery.',[],'Springer / Palgrave','chapter_abstract')
    node(d,'person_eric_trist','Eric Trist','person','Eric Lansdown Trist (1909–1993) worked on sociotechnical systems and organisation design. The cited chapter abstract also describes action research and his work with Fred Emery.',[ts],['sociotechnical','organisation'],['Eric L. Trist','Eric Lansdown Trist'])
    rs=source(d,'src_robert_rosen_archive_2026','Robert Rosen scientific-work archive','https://www.rosenlife.org/','Archive landing page inspected; identifies Rosen as a biologist and provides routes into the scientific-work collection. Detailed theoretical claims in the submission remain unreviewed.',['Robert Rosen archive'],'Rosenlife','author_archive')
    node(d,'person_robert_rosen','Robert Rosen','person','A biologist whose archive provides access to work across biology, complexity, mathematics and epistemology. This entry identifies the collection; the submitted claims about anticipatory systems require a separate close-reading pass.',[rs],['biology','systems'])
    # Remove an unowned evaluative sentence; avoid asserting a named human review of this revision.
    p=next(p for p in d['profiles'] if p['node_id']=='person_david_ing')
    p['common_misreadings']=enc(['Documented association is not by itself evidence of intellectual influence.'])
    p['summary']='Ing’s public work includes service-systems research, systems-changes learning, teaching and documentation of systems scholarship. The linked source records identify the basis and limits of this account.'
    p.update(review_status='source_scoped_research_pass',profile_status='source_scoped_research_pass',reviewed_by='',reviewed_at='',editorial_note='This account and its framing were prepared with AI assistance. The source records support documentary claims; evaluative and practice interpretations are editorial and open to challenge. No new independent review or contributor role is implied.',last_researched=DATE)
    # Both public curriculum versions remain visible; teaching order is not an influence claim.
    curriculum=json.loads((ROOT/'sources/september-2026/leading-transformation.json').read_text())
    curriculum_nodes=[]
    for version,filename in [('original','leading-transformation.json'),('revised','curriculum-2026.json')]:
        sid=source(d,'src_sep_lt_'+version,'Leading Transformation: '+curriculum[version]['label'],'https://github.com/antlerboy/PSTA/blob/main/content/'+filename,'Public programme module register inspected. This is an educational route, not evidence of an intellectual lineage or a delivery commitment.',['RedQuadrant','Public Service Transformation Academy'],'Public Service Transformation Academy','public_curriculum')
        nid=node(d,'corpus_leading_transformation_'+version,'Leading Transformation: '+curriculum[version]['label'],'corpus','A 24-module learning architecture for public-service transformation. Both this version and the other dated version remain available for comparison.',[sid],['education','practice','public-services']);curriculum_nodes.append(nid)
        for target,locator in [('method_or_methodology_viable_system_model_vsm','Original modules 3 and 8; revised module 17'),('intervention_skill_lean_and_six_sigma','Original module 16; revised module 13: Lean component only, not Six Sigma'),('method_or_methodology_patterns_of_strategy','Original module 23; revised module 21'),('intervention_skill_appreciative_inquiry','Original module 21; revised module 23')]:
            edge(d,nid,target,'offers_reading_route_to','documentary','offers a learning route to',[sid],locator,'The module summary names this approach. Selection for practice does not establish theoretical equivalence, intellectual influence or effectiveness.')
    d['versioned_curriculum']=curriculum
    current_rows=''.join('<tr id="module-'+str(m['number'])+'"><td>'+str(m['number'])+'</td><td>'+html.escape(m['title'])+'<br><small>'+html.escape(m['worldLabel'])+'</small></td><td>'+html.escape(m['focus'])+'</td></tr>' for m in curriculum['revised']['modules'])
    legacy_rows=''.join('<tr><td>'+str(m['number'])+'</td><td>'+html.escape(m['title'])+'<br>'+html.escape(m['description'])+'</td><td>'+', '.join('<a href="#module-'+str(n)+'">'+str(n)+'</a>' for n in link['revised'])+'</td></tr>' for m,link in zip(curriculum['original']['modules'],curriculum['correspondence']))
    page('learning/leading-transformation','Leading Transformation: two dated learning routes','<p>Leading Transformation is the Public Service Transformation Academy’s programme. RedQuadrant’s Tool Shed is a supported practitioner learning and application offer using related content. The original 24-module architecture is retained here alongside the revised route agreed on 6 September 2026.</p><p><a href="https://www.publicservicetransformation.org/programmes/leading-transformation/">Leading Transformation programme</a> · <a href="https://www.redquadrant.com/toolshed/">RedQuadrant Tool Shed</a></p><h2>Revised route: 6 September 2026</h2><p>The five worlds are perspectives with cross-links: leadership and political; citizen; service; management; learning and change. Five Core Practices recur throughout. Live work begins in module 3, service prototyping in module 12, and the Four Dynamics are introduced in module 4 and applied in module 18. The final simulation requires a substantial delivery block and hundred-day follow-through.</p><table><thead><tr><th>Module</th><th>Focus and world</th><th>Practice</th></tr></thead><tbody>'+current_rows+'</tbody></table><h2>Original route: 2020–2025 source versions</h2><p>The final column is an AI-assisted editorial correspondence between the public summaries. It helps readers find material across versions; it does not claim formal equivalence. New emphases include explicit relational public services, digital/data/AI judgement, and the Four Dynamics.</p><table><thead><tr><th>Original module</th><th>Title and content</th><th>Related revised modules</th></tr></thead><tbody>'+legacy_rows+'</tbody></table><h2>Follow the concepts</h2><p><a href="/#view=item&amp;id=method_or_methodology_viable_system_model_vsm">Viable System Model</a> · <a href="/#view=item&amp;id=intervention_skill_lean_and_six_sigma">Lean: operational learning</a> · <a href="/#view=item&amp;id=method_or_methodology_patterns_of_strategy">Patterns of Strategy</a> · <a href="/#view=item&amp;id=intervention_skill_appreciative_inquiry">Appreciative Inquiry</a></p><p>The source register distinguishes dated curriculum facts from these editorial connections. A module sequence does not establish intellectual influence. Core learning, optional depth, supported application and demonstrated competence remain different things. See the programme providers for current arrangements.</p><p>Sources: <a href="https://github.com/antlerboy/PSTA/blob/main/content/leading-transformation.json">Original public module register</a> and <a href="https://github.com/antlerboy/PSTA/blob/main/content/curriculum-2026.json">Revised public module register</a>. Prepared with AI assistance; independent specialist review is not recorded.</p>')
    # Public queue reconciliation tracks scope without copying submitted evaluative assertions into the atlas.
    intake=json.loads((ROOT/'sources/september-2026/queue.json').read_text())
    for item in intake:
        label=item['name'];wanted=slug(label)
        aliases={ 'Eric L. Trist':['Eric Trist'],'James J. Kay':['James Kay'],'Ian I. Mitroff':['Ian Mitroff'],'Kyoichi (Jim) Kijima':['Kyoichi Kijima','Jim Kijima'],'International Society for the Systems Sciences':['ISSS'],'International Federation for Systems Research':['IFSR'] }.get(label,[])
        found=next((n for n in d['nodes'] if n['label']==label or n['label'] in aliases or any(a in parse(n.get('aliases')) for a in [label]+aliases)),None)
        item['canonical_id']=d.get('canonical_redirects',{}).get(found['id'],found['id']) if found else None
        item['status']='existing_entry_deeper_claims_pending' if found else 'source_review_pending'
    d['september_connections']={'reviewed':DATE,'scope':'Located connections, bibliography route, source and editorial attribution','source_limit':'OCAD pro forma retrieval unavailable; module-level summary and deeper submission claims remain open.','queue':intake}
    refresh_counts(d);d['relational_depth']=calculate_relational_depth(d);d['relational_depth'].update(release=d['meta']['release'],generated=DATE);d['graph_snapshot']=calculate(d)
    metrics=graph_metrics(d);d['meta'].update(generated=DATE,connection_pass=MARK,connection_pass_url='https://transduction.systems/updates/2026-09-09/',node_count=len(d['nodes']),edge_count=len(d['edges']),source_count=len(d['sources']),profile_count=len(d['profiles']),public_entry_count=metrics['public_entries'],described_entry_count=metrics['public_entries'])
    for k,v in [('reader_connected_entry_count','reader_connected_entries'),('semantic_connected_entry_count','semantic_connected_entries')]:d['meta'][k]=d['relational_depth']['aggregate'][v]
    write(d);write_relational_document(d)
    rows=''.join('<tr><td><a href="'+html.escape(url)+'">'+html.escape(title)+'</a></td><td>'+html.escape(notes)+'</td><td><a href="/#view=item&amp;id='+nid+'">Atlas entry</a></td></tr>' for (_,title,url,_,_,notes,_),nid in zip(bibli,works))
    page('corpora/ing-ocad','David Ing’s OCAD reading route','<p class="note">This guide covers the six core resources in the supplied recommendation. The complete <a href="'+next(s['url'] for s in d['sources'] if s['id']==ocad)+'">13-week course pro forma</a> could not be retrieved for this pass. A module-by-module guide and close reading of its additional papers remain open.</p><p>The recommendation identifies Stephen N. Davies as the winter 2026 course instructor and David Ing as a volunteer contributor. These are distinct roles.</p><h2>Follow the readings</h2><table><thead><tr><th>Resource</th><th>What has been checked</th><th>Connection</th></tr></thead><tbody>'+rows+'</tbody></table><h2>One explicit comparison</h2><p>Reynolds and Holwell’s introductory abstract compares SD, VSM, SODA, SSM and CSH. Its rationale concerns change and uncertainty, constructivist use, and combinations of methods. <a href="https://link.springer.com/chapter/10.1007/978-1-4471-7472-1_1">Read the chapter abstract and access options</a>. This is abstract-level evidence, not a claim to have read the subscription chapter.</p><h2>How to read the connections</h2><p>Selection for teaching, authorship, a conceptual comparison and historical influence are different statements. The map records which kind is being made. A course’s order is not evidence that one author influenced the next.</p><p>Prepared with AI assistance from named sources. Evaluations and proposed practice uses remain editorial contributions, open to correction. No contributor role or independent review is implied.</p>')
    n_edges=sum(e['id'].startswith('e24_') for e in d['edges'])
    queue_rows=''.join('<tr><td><a href="'+i['url']+'">'+html.escape(i['name'])+'</a></td><td>'+('Existing entry: <a href="/#view=item&amp;id='+i['canonical_id']+'">open</a>; submitted claims require separate review.' if i['canonical_id'] else 'Source review remains open; no unsupported profile has been manufactured.')+'</td></tr>' for i in intake)
    page('updates/2026-09-09','Source connections and events: 9 September 2026',f'<p>{n_edges} source-scoped statements connect reading resources, authors, methods and concepts. Every new statement includes a source locator and a scope limit.</p><ul><li><a href="/corpora/ing-ocad/">Ing’s OCAD reading route</a>: six resources, with full-course retrieval and article reading explicitly outstanding.</li><li><a href="/#view=item&amp;id={femid}">FEM</a>: toolkit, VSM coordination, recursive units and structural coupling.</li><li><a href="/#view=item&amp;id={paper}">Taylor and Boxer’s working paper</a>: a versioned connection to relational practice and organisational conditions.</li><li><a href="/learning/leading-transformation/">Leading Transformation</a>: both 24-module versions and an explicit editorial correspondence.</li><li><a href="/events/?topic=relational-public-services">Relational public services events</a>: separate heading and calendar subscription.</li></ul><h2>Evidence and editorial authorship</h2><p>AI-assisted synthesis is labelled. Documentary links establish specific facts; they do not establish quality, influence or endorsement. A revised Ing profile removes an unattributed evaluative sentence and does not claim that a named person reviewed this revision.</p><h2>Outstanding source submissions</h2><p>These submissions remain open. Matching an identity is different from checking all the claims in a submission. Participation requests and the Jackson/Snowden lecture require separate discussion or source review.</p><table><thead><tr><th>Submission</th><th>Disposition</th></tr></thead><tbody>'+queue_rows+'</tbody></table><p><a href="https://github.com/antlerboy/the-necessary-tangle/issues/2">Maintained update queue</a></p>')
    for file in ['reading-list.html','updates/index.html']:
        p=ROOT/'docs'/file
        if p.exists():
            t=p.read_text();a='<!-- september-links -->';b='<!-- /september-links -->';t=re.sub(re.escape(a)+r'.*?'+re.escape(b),'',t,flags=re.S);t=t.replace('</main>',a+'<section><h2>September source connections</h2><p><a href="/corpora/ing-ocad/">Ing’s OCAD reading route</a> · <a href="/learning/leading-transformation/">Two Leading Transformation routes</a> · <a href="/updates/2026-09-09/">Connections, evidence and remaining work</a></p></section>'+b+'</main>',1);p.write_text(t)
    p=ROOT/'docs/sitemap.xml';t=p.read_text()
    for route in ['corpora/ing-ocad/','updates/2026-09-09/','learning/leading-transformation/']:
        u='https://transduction.systems/'+route
        if u not in t:t=t.replace('</urlset>','<url><loc>'+u+'</loc><lastmod>'+DATE+'</lastmod></url></urlset>')
    p.write_text(t)
    summary=f'## 9 September 2026 source connection pass\n\nAdded {n_edges} typed, source-scoped statements; OCAD reading entrance, FEM applications, Taylor/Boxer paper and Benjamin P Taylor entry. Publication was explicitly requested. AI authorship and unreviewed interpretation are labelled. The complete OCAD pro forma could not be retrieved; module-level close reading, the larger source-submission claims and participation roles remain open. See the public dated update and sources/september-2026/queue.json.\n\n'
    for name in ['TANGLE_STATE.md','NEXT_WORK.md']:
        p=ROOT/'documentation'/name;t=p.read_text()
        if '## 9 September 2026 source connection pass' not in t:p.write_text(summary+t)
    (ROOT/'documentation/september-2026-connections.md').write_text(summary+'The pipeline applies this pass after the practice pack and regenerates public data, relational depth and the graph snapshot. Protected comparator assets and existing practice pages are retained.\n')
    print(f'September pass: {n_edges} statements; {len(d["nodes"])} records; {len(d["profiles"])} profiles')
    (ROOT/'sources/september-2026/base-records.json').write_text(json.dumps(BASE,ensure_ascii=False,indent=2)+'\n')
if __name__=='__main__':main()
