"""Develop the curator's entry from located public work, without inferred prestige."""
from apply_iteration_17 import enc,upsert,relation_record,merge_encoded

def apply(data,records,source,newnode,edge):
    person='person_benjamin_p_taylor'
    nodes={n['id']:n for n in data['nodes']}
    author=source('src_taylor_public_profile_20260919','Benjamin P Taylor: public work and roles','https://antlerboy.com/','What I do; Work; Thinking and writing; Ways into the work. First-person role and collection statements checked 19 September 2026.','author_profile',['Benjamin P Taylor'])
    atlas=source('src_tangle_curator_20260919','The Necessary Tangle: curator and purpose','https://transduction.systems/#view=about','Home page Curator section and About. Identifies the project curator, its purpose, and its relation to the earlier SysBoK.','project_documentation')
    def record(title):return next(r for r in records if r['title']==title and r.get('pages'))
    def sid(item):return next(s['id'] for s in data['sources'] if s.get('url')==item['url'])
    for typ,family,inverse,minimum,phrase in [
        ('has_public_leadership_role','human','has_public_leader','A dated first-person or institutional role statement','has a documented leadership role in'),
        ('serves_on_board_of','human','has_board_member','A dated first-person or institutional board statement','serves on the board of'),
        ('curates_public_collection','practice','is_curated_by','A public attribution of responsibility for the collection','curates'),
        ('writes_at','documentary','publishes_writing_by','An explicit author account of the publication venue','publishes writing at'),
        ('teaches_subject','teaching','is_taught_by','A named teaching account and specific subject locator','teaches'),
        ('presents_practice_synthesis','practice','has_practice_synthesis_by','A signed presentation explaining the synthesis and its antecedents','presents a practice synthesis of'),
        ('draws_on_in_synthesis','historical','is_drawn_on_in_synthesis_by','An explicit statement naming the people drawn on in a specified work','draws on in this practice synthesis'),
    ]:upsert(data['relation_types'],[relation_record(typ,family,inverse,minimum,phrase)],'relation_type')
    organisations=[
        ('organisation_redquadrant','RedQuadrant','A UK public-service transformation consultancy led by Benjamin P Taylor. Its public work covers organisational and service change, including building capability for systems practice.'),
        ('organisation_public_service_transformation_academy','Public Service Transformation Academy','A social enterprise supporting public services to build their own capability to transform, through learning, development, and work on live service challenges.'),
    ]
    for nid,label,description in organisations:
        newnode(nid,label,'organisation',description,[author])
        edge(person,nid,'has_public_leadership_role','human','leads',[author],'Antlerboy: What I do and Work; checked 19 September 2026','Current first-person public role statement. This relation does not assert that every organisational publication or intervention is his individual work.')
    edge(person,'organisation_scio_systems_and_complexity_in_organisation','serves_on_board_of','human','serves on the board of',[author],'Antlerboy: What I do and SCiO; checked 19 September 2026','Board membership and contribution to professional practice and events, as stated in the public profile.')
    newnode('corpus_systems_community_of_inquiry','Systems Community of Inquiry','corpus','An open curation and discussion stream for systems, cybernetics, and complexity, maintained by Benjamin P Taylor. Its posts point to many authors and organisations; inclusion is not a claim that Taylor authored or endorses the linked work.',[author])
    newnode('corpus_chosen_path','Chosen Path','corpus','Benjamin P Taylor’s blog and archive of essays, working notes, and arguments. The source register indexes its public posts; individual entries retain their dates and source links.',[author])
    newnode('corpus_necessary_tangle','The Necessary Tangle','corpus','A public atlas connecting systems, cybernetics, and complexity through explicit relationships between people, ideas, practices, works, and institutions. Curated by Benjamin P Taylor.',[atlas])
    for target,s,loc in [('corpus_antlerboy_public_library',author,'Antlerboy: Public work library'),('corpus_systems_community_of_inquiry',author,'Antlerboy: Systems Community of Inquiry'),('corpus_necessary_tangle',atlas,'The Necessary Tangle: Curator section')]:
        edge(person,target,'curates_public_collection','practice','curates',[s],loc,'Collection responsibility, not authorship of every item, endorsement of every argument, or ownership of source rights.')
    edge(person,'corpus_chosen_path','writes_at','documentary','publishes writing at',[author],'Antlerboy: Thinking and writing, chosen path','Author’s public identification of the writing venue; individual posts remain separately inspectable.')
    # Authorship is checked against named title pages, not inferred from hosting.
    authored_titles=['Positive dynamics of differentiation and integration; ISSS','Degrees of relationality','The demand side of public services','Anxiety, ideology and the evacuation of the public realm','Systems leadership, change, theory and practice','Introduction to four dynamics','A simplification of the Viable System Model','Viable System Model lecture','Power, systems, and the Viable System Model','Clarity practices','Large-group processes','Better conversations for better realities']
    credit_sources=[]
    for title in authored_titles:
        item=record(title);s=sid(item);credit_sources.append(s)
        item['authors']=['Benjamin P Taylor']
        next(record for record in data['sources'] if record['id']==s)['creators']=enc(item['authors'])
        edge(item['atlas_id'],person,'authored_by','documentary','is authored or presented by',[s],'PDF page 1: named author or presenter','The title page names Benjamin Taylor. Co-authors and other credited intellectual sources retain their attribution; this does not claim sole authorship or origination of methods taught.')
        item['connections'].append(dict(target=person,label='Benjamin P Taylor',kind='authorship',locator='PDF page 1: named author or presenter',status='Public title-page credit checked'))
    degrees=record('Degrees of relationality')
    edge(person,'person_philip_boxer','coauthored_with','human','co-authored with',[sid(degrees),sid(record('The demand side of public services'))],'Degrees of relationality v12, p. 1; The demand side of public services v9, p. 1','Documented co-authorship of the linked working papers. No teaching, mentorship, or direction of influence is inferred.')
    dynamics=record('Positive dynamics of differentiation and integration; ISSS');clarity=record('Clarity practices')
    newnode('model_taylor_four_dynamics','Four dynamics of organisation (Taylor)','method_or_methodology','A practice synthesis of differentiation, integration, individuation, and homogenisation, developed through the complementary practices segment, blend, empower, and harmonise. Taylor’s 2024 account explicitly draws on Barry Oshry, Stafford Beer, and Sandra Janoff. The model is a working account for inquiry and organisation, not a universal causal law.',[sid(dynamics),sid(record('Introduction to four dynamics'))])
    newnode('practice_taylor_five_core_practices','Five core leadership practices (Taylor)','practice','A teaching framework joining constructive conversations, clarity, triple-loop learning, culture shaping, and good and clear intent. The first three are presented as foundations for a learning system; culture and intent concern productivity and purpose. The relationships are propositions in the cited practice account, rather than independent efficacy findings.',[sid(clarity)])
    for target,item,loc in [('model_taylor_four_dynamics',dynamics,'PDF pp. 1–3; Introduction to four dynamics, pp. 7–12'),('practice_taylor_five_core_practices',clarity,'PDF pp. 1 and 5–7')]:
        edge(person,target,'presents_practice_synthesis','practice','presents a practice synthesis of',[sid(item)],loc,'Named public teaching work. This relation identifies Taylor’s account while preserving its stated intellectual antecedents.')
        edge(item['atlas_id'],target,'teaching_account_of','teaching','presents a teaching account of',[sid(item)],loc,'Teaching coverage, not independent evaluation.')
        item['connections'].append(dict(target=target,label=next(n['label'] for n in data['nodes'] if n['id']==target),kind='teaching_account',locator=loc,status='Located teaching account'))
    for target in ['person_barry_oshry','person_stafford_beer','person_sandra_janoff']:
        edge('model_taylor_four_dynamics',target,'draws_on_in_synthesis','historical','draws on work by',[sid(dynamics)],'PDF page 3: What I want to cover','Taylor explicitly names the three people whose ideas he draws on for this model. This does not assert personal contact, mentorship, or exclusive intellectual ancestry.')
    teaching=[('Systems leadership, change, theory and practice','approach_family_systems_leadership','PDF pp. 1, 3–4'),('Systems leadership, change, theory and practice','approach_family_systems_change','PDF pp. 1, 3–4'),('Systems leadership, change, theory and practice','practice_systems_practice','PDF pp. 1, 3–4'),('Systems leadership, change, theory and practice','practice_systems_convening','PDF pp. 3–4'),('A simplification of the Viable System Model','method_or_methodology_viable_system_model_vsm','PDF pp. 1–3'),('Better conversations for better realities','intervention_skill_productive_conversations','PDF p. 1 and teaching account')]
    for title,target,loc in teaching:
        item=record(title)
        edge(person,target,'teaches_subject','teaching','teaches',[sid(item)],loc,'A located subject in Taylor’s public teaching. Teaching a method is distinct from originating it, and from a claim that it works in every context.')
    edge(person,'practice_relational_public_services','presents_practice_synthesis','practice','develops a practitioner account of',[sid(degrees)],'Degrees of relationality v12, pp. 1–3','Co-authored with Philip Boxer. The ladder is explicitly a practitioner-derived heuristic, not a validated scale or universal maturity sequence.')
    definition='Systems practitioner, educator, and writer working on public-service transformation, organisational capability, and the use of systems and cybernetic ideas in practice. He leads RedQuadrant and the Public Service Transformation Academy, serves on the SCiO board, and curates the Systems Community of Inquiry and The Necessary Tangle.'
    node=nodes[person];node.update(description=definition,canonical_definition=definition,publication_level='profile',review_status='source_scoped_ai_assisted',reviewed_by='',reviewed_at='')
    profile_sources=[author,atlas,*credit_sources];merge_encoded(node,'source_ids',profile_sources)
    profile=dict(node_id=person,title='Benjamin P Taylor',profile_status='source_scoped_ai_assisted',canonical_definition=definition,
        summary='Taylor’s public work moves between work with services and organisations, practitioner education, writing, and community curation. His teaching includes the Viable System Model (VSM), large-group processes, constructive conversations, and distinctions between systems leadership, systems change, systems practice, and systems convening. His current papers with Philip Boxer examine relational public services, demand, organisational boundaries, and the conditions under which learning can change an institution’s response.',
        why_it_matters='The contribution represented here is the work of translating, combining, testing, and teaching ideas in public-service and organisational settings. Examples include the four dynamics of organisation, five core leadership practices, and the degrees-of-relationality heuristic. These should be read as specific, attributable practice accounts with their own sources and limits. The public archive also offers a route from a problem in practice to a teaching account, an underlying concept, and competing ways of framing it.',
        key_distinctions=enc(['Systems leadership, systems change, systems practice, and systems convening do different work, even where they overlap.','A reliable transaction can be appropriate; relationality is not automatically an improvement.','Teaching, adaptation, authorship, and curation are different contributions.','An organisation’s service categories do not exhaust what matters in a citizen’s life.']),
        historical_lineage=enc(['Four dynamics: the 2024 ISSS presentation explicitly names Barry Oshry, Stafford Beer, and Sandra Janoff as sources for the synthesis.','Management cybernetics and the Viable System Model appear in named public lectures and practical adaptations.','Co-authored working papers with Philip Boxer address asymmetric demand and relational public-service reform.']),
        logical_antecedents=enc(['Viable System Model','Boundaries and organisational capability','Learning, constructive conversation, and public purpose']),
        dependent_subsequents=enc(['Four dynamics of organisation (Taylor)','Five core leadership practices (Taylor)','Degrees of relationality: a ladder for public service design','The Necessary Tangle and the public work library']),
        practice_connections=enc(['Public-service transformation and capability development through RedQuadrant and PSTA','SCiO professional practice, events, and education','Systems convening and work across organisational boundaries','Large-group facilitation and participation','Public writing at Chosen Path and curation through SysCoI']),
        espoused_lineages=enc(['Oshry, Beer, and Janoff are explicitly named in the four-dynamics presentation; this is not a general claim of personal mentorship.']),observed_clusters='[]',
        common_misreadings=enc(['Hosting or curating a work does not make Taylor its author.','The degrees-of-relationality ladder is a heuristic, not a moral ranking or validated maturity scale.','Presenting the VSM does not imply originating it.']),
        open_checks=enc(['Add independent accounts of practice and outcomes, distinguishing testimony from evaluated evidence.','Continue reconciling older writing and training records, including editions and co-author credits.','Develop further passage-level connections from the four requested research collections.']),
        source_ids=enc(profile_sources),evidence_ids='[]',last_researched='2026-09-19',review_status='source_scoped_ai_assisted',reviewed_by='',reviewed_at='',editorial_note='Expanded from public role statements, named teaching pages, and working-paper title pages. Prepared with AI assistance; no independent specialist review is claimed. Current roles rely on the dated first-person public profile. The curator is also the subject, which readers should take into account.')
    upsert(data['profiles'],[profile],'node_id')
