"""Reproducible current reading intake, with source-scoped graph statements."""
from pathlib import Path
import html,json,re,math,hashlib
from apply_iteration_17 import enc,parse,upsert,source_record,node_record,profile_record,edge_record
from apply_iteration_09 import graph_metrics,make_ai_observations
from apply_relational_depth_16 import calculate_relational_depth,write_relational_document
from apply_doncaster_lineage import refresh_counts
from apply_overnight_review import quality_result
from refresh_graph_snapshot import calculate,write
import apply_iteration_10 as observations_doc
ROOT=Path(__file__).resolve().parents[1];DOCS=ROOT/'docs';MARK='update_20261007';DATE='2026-10-07';RELEASE='0.30'
P=json.loads((ROOT/'sources/update-2026-10-07/review.json').read_text())
d=json.loads((ROOT/'data/public-data.json').read_text());E=lambda x:html.escape(str(x),quote=True)
def source(sid,title,url,summary,creators=[],publisher='',year='2026',locator=''):
    r=source_record(sid,title,'public_source',url,summary,creators,publisher,year,quality='B')
    r.update(connection_pass=MARK,last_checked=DATE,review_status='source_scoped_research_pass',source_locator=locator)
    upsert(d['sources'],[r],'id');return sid
def node(nid,title,kind,summary,sids,tags=[]):
    i=int(hashlib.sha256(nid.encode()).hexdigest()[:6],16)
    r=node_record(nid,title,kind,summary,sids,round(0.55+0.2*math.cos(i*2.4),6),round(0.45+0.2*math.sin(i*2.4),6),tags)
    r.update(connection_pass=MARK,status='candidate',review_status='research_pass_needs_editor',reviewed_by='',reviewed_at='',inclusion_reason=MARK,set_tags=enc(['systems','release_0_30',*tags]))
    upsert(d['nodes'],[r],'id');return nid
def edge(eid,a,b,typ,sid,locator,scope):
    family=next(r['relation_family'] for r in d['relation_types'] if r['relation_type']==typ)
    r=edge_record(eid,a,b,typ,family,typ.replace('_',' '),[sid],locator,scope,status='candidate',confidence='',review_label='Located source statement; curator review pending')
    vid='ev_'+eid;cid='claim_'+eid;r.update(connection_pass=MARK,evidence_ids=enc([vid]),claim_id=cid)
    upsert(d['edges'],[r],'id')
    upsert(d['evidence'],[dict(id=vid,source_id=sid,locator=locator,excerpt_or_summary=scope,evidence_type='located_public_source',quality_tier='B',licence='source terms',review_status='research_pass_needs_editor',content_hash='',public_evidence_status='public',connection_pass=MARK)],'id')
    upsert(d['claims'],[dict(id=cid,statement=scope,subject_id=a,predicate=typ,object_id=b,status='candidate',supporting_source_ids=enc([sid]),supporting_evidence_ids=enc([vid]),contradicting_source_ids='[]',contradicting_evidence_ids='[]',notes='Scope is limited to the identified source passage.',review_status='research_pass_needs_editor',reviewed_by='',reviewed_at='',connection_pass=MARK)],'id')
bio=source('src_u30_schot_bio','Johan Schot: official profile','https://www.johanschot.com/','Official professional profile; self-description, not independent evaluation.',['Johan Schot'],'Johan Schot',locator='Opening professional biography')
pathways=source('src_u30_transition_pathways','Typology of Sociotechnical Transition Pathways','https://www.johanschot.com/publications/typology-of-sociotechnical-transition-pathways/','Author publication page and abstract: four pathways differentiated by timing and nature of interactions.',['Frank Geels','Johan Schot'],'Research Policy','2007',locator='Abstract and citation')
mlps=source('src_u30_mlp_chapter','The Multi-level Perspective on Sustainability Transitions','https://doi.org/10.1017/9781009437318.004','Open chapter: analytical levels, transition dynamics and current developments.',['Frank Geels'],'Cambridge University Press',locator='Chapter 2, sections 2.1 and 2.4')
dts=source('src_u30_dt_chapter','Deep Transitions','https://doi.org/10.1017/9781009437318.009','Open chapter: multi-system change, shared rules, criticisms and further research.',['Jack Davies','Johan Schot'],'Cambridge University Press',locator='Chapter 7, sections 7.1, 7.2 and 7.3.5')
found=source('src_u30_dt_founding','Deep transitions: Emergence, acceleration, stabilization and directionality','https://deeptransitions.net/wp-content/uploads/2022/11/Deep-Transitions_Emergence-acceleration-stabilization-and-directionality.pdf','Founding framework paper. Shared rules are distinguished from rule-sets; the proposed sustainable transition is not a predicted certainty.',['Johan Schot','Laur Kanger'],'Research Policy','2018',locator='PDF page 9: rules, meta-rules, regimes and meta-regimes')
policy=source('src_u30_three_frames','Three frames for innovation policy: R&D, systems of innovation and transformative change','https://tipconsortium.net/publication/three-frames-for-innovation-policy-rd-systems-of-innovation-and-transformative-change/','Distinguishes R&D support, innovation systems and transformative change addressing social and environmental challenges. Publisher or author account; not a general intervention recipe.',['Johan Schot','W. Edward Steinmueller'],'Research Policy','2018',locator='Article abstract and three policy framings')
guide=source('src_u30_dt_guide','A Guide to Deep Transitions','https://deeptransitions.net/publication/a-guide-to-deep-transitions/','Project introduction and glossary; a reading starting point, not independent validation.',[],'Deep Transitions',locator='Guide introduction and linked glossary')
schot=node('person_johan_schot','Johan Schot','person','Historian working on socio-technical change and sustainability transitions. His official profile identifies him as Professor of Global History and Sustainability Transitions at Utrecht University.',[bio,pathways,dts,found],['transitions'])
geels=node('person_frank_geels','Frank Geels','person','Transition researcher, author of the 2026 multi-level perspective overview and co-author with Johan Schot of the 2007 transition pathways paper.',[mlps,pathways],['transitions'])
kanger=node('person_laur_kanger','Laur Kanger','person','Co-author with Johan Schot of the 2018 Deep Transitions framework paper. This entry establishes that contribution without claiming sole origin of the wider research field.',[found],['transitions'])
mlp=node('framework_multi_level_perspective','Multi-level perspective on socio-technical transitions','framework','An analytical account of transitions through interactions among protected innovation niches, established socio-technical regimes, and wider landscape pressures. The levels describe different forms of structuration, not an organisational hierarchy or a sequence of implementation stages.',[mlps,pathways],['transitions'])
dt=node('framework_deep_transitions','Deep Transitions','framework','A research framework for long-term change across multiple socio-technical systems. Shared rules help explain common directions such as fossil-fuel dependence; a proposed Second Deep Transition towards sustainability and justice remains an ambition and research proposition.',[found,dts,guide],['transitions'])
meta=node('concept_transition_meta_rules','Meta-rules in Deep Transitions','concept','In Deep Transitions, a meta-rule is a rule shared across more than one socio-technical system. A meta-regime is a shared rule-set. These technical terms concern cross-system directionality rather than any general rule about rules.',[found,dts],['transitions'])
pub=node('publication_geels_schot_pathways_2007','Typology of sociotechnical transition pathways (2007)','publication','Frank Geels and Johan Schot distinguish transformation, reconfiguration, technological substitution, and de-alignment and re-alignment. The abstract relates their differences to timing and nature of multi-level interactions.',[pathways])
dp=node('publication_schot_kanger_deep_transitions_2018','Deep transitions: Emergence, acceleration, stabilization and directionality (2018)','publication','Johan Schot and Laur Kanger propose an account of connected historical change across socio-technical systems. The framework distinguishes rules within a system from rules shared across systems.',[found])
for a,b,s,l in [(pub,schot,pathways,'Citation'),(pub,geels,pathways,'Citation'),(dp,schot,found,'PDF page 1: authors'),(dp,kanger,found,'PDF page 1: authors')]:edge('e30_auth_'+a+'_'+b,a,b,'authored_by',s,l,'Authorship of this named publication only; no general lineage or priority claim.')
edge('e30_pathways_mlp',pub,mlp,'presents_account_of',pathways,'Abstract','The paper refines the multi-level perspective and distinguishes four transition pathways; full case-by-case reassessment is not claimed.')
edge('e30_found_dt',dp,dt,'presents_account_of',found,'Abstract and framework discussion','The paper proposes the Deep Transitions framework; this relation does not establish that the whole theory has been empirically confirmed.')
edge('e30_found_meta',dp,meta,'introduces_distinction',found,'PDF page 9: four definitions','A meta-rule is a rule shared across multiple systems; a meta-regime is a shared rule-set.')
for nid in [schot,geels,kanger,mlp,dt,meta,pub,dp]:
    n=next(x for x in d['nodes'] if x['id']==nid)
    r=profile_record(nid,n['description'],'Use the cited source to distinguish an analytical account from a proposed intervention.',['source account vs editorial application','single-system change vs cross-system rules'],[],[],[],['Specify the rule, its enforcement and who can change it.'],['Treating transition levels as VSM systems or organisational ranks.'],['Independent expert review and further empirical comparison remain open.'],parse(n['source_ids']),editorial_note='Prepared with AI assistance; source-scoped first pass. Curator: Benjamin P Taylor.')
    r.update(connection_pass=MARK,title=n['label'],last_researched=DATE,review_status='research_pass_needs_editor',profile_status='evidence_deepened_research_pass');upsert(d['profiles'],[r],'node_id')
collection_source=source('src_u30_syscoi_collection','SysCoI recent additions: 21 September–7 October 2026',P['api'],'Public WordPress discovery response; 31 published posts. Linked content is not treated as independently verified.',['Systems Community of Inquiry'],'SysCoI',locator='Published post IDs and dates in this response')
collection=node('collection_syscoi_october_2026','SysCoI: recent additions, October 2026','collection','A dated collection of all 31 posts returned for the period after 19 September through 7 October 2026. It includes announcements, commentary and reading leads; collection membership does not validate a post’s substantive claims.',[collection_source])
for row in P['posts']:
    sid=source('src_syscoi_post_'+str(row['id']),row['title'],row['url'],'SysCoI post published '+row['date'][:10]+'. Discovery record; linked sources and substantive claims require separate review.',[],'SysCoI',locator='Post title, date and outbound links')
    nid=node('publication_syscoi_post_'+str(row['id']),row['title'],'publication','SysCoI reading or event lead published '+row['date'][:10]+'. This atlas record points to the public post and its source links. It does not certify claims in the linked material or infer authorship from a title.',[sid],['syscoi-intake'])
    edge('e30_collection_'+str(row['id']),collection,nid,'catalogues_resource',sid,'Post ID '+str(row['id'])+'; title and published date','Documentary membership of this dated reading collection only; no conceptual influence or endorsement implied.')
toolsrc=source('src_u30_orglens','OrgLens README','https://framagit.org/dynamicskillset/orglens','Maintainer description. Formerly VSMkit; current evidence concerns fictional test organisations, not demonstrated outcomes in real organisations.',['Doug Belshaw / Dynamic Skillset'],'Dynamic Skillset',locator='README introduction, three lenses and What we have found')
tool=node('tool_orglens','OrgLens (formerly VSMkit)','tool','An experimental organisational health-check tool. Its README describes lenses for feedback loops, the Viable System Model, and perspectives and boundaries using SSM and CSH. Reported trials use fictional organisations, simulated participants and AI judges; real-organisation effectiveness is not established.',[toolsrc],['tools'])
vsm='method_or_methodology_viable_system_model_vsm'
edge('e30_orglens_vsm',tool,vsm,'uses',toolsrc,'README: How is it set up? and test limitations','The maintainer describes VSM as one analytical lens. This documents the tool’s method claim, not independent validation of its diagnoses.')
coding_url='https://derroth.com/2026/10/05/release-special-issue-of-itp-on-coding-society-programmatic-encounters-between-information-systems-and-social-theory/'
coding_source=source('src_u30_coding_society','Coding Society special issue: release announcement',coding_url,'Announcement and recommended citation checked. Information Technology & People, volume 39, issue 6. Individual articles are linked but not reviewed.',['Steffen Roth'],'Dr Steffen Roth',locator='5 October 2026 announcement: Contributions and recommended citation')
node('publication_coding_society_special_issue_2026','Coding Society: Programmatic Encounters Between Information Systems and Social Theory','publication','A 2026 special issue of Information Technology & People, volume 39, issue 6, announced by Steffen Roth. This record establishes the publication lead and bibliographic scope; it does not claim review of the individual articles or classify publication as an event.',[coding_source],['queued-reading'])
d[MARK]=dict(release=RELEASE,post_count=len(P['posts']),reader_url='/reading/socio-technical-transitions/',digest_url='/updates/2026-10-07/',queue=P['queue'])
refresh_counts(d);d['relational_depth']=calculate_relational_depth(d);d['relational_depth'].update(release=RELEASE,generated=DATE);d['graph_snapshot']=calculate(d);metrics=graph_metrics(d);depth=d['relational_depth']['aggregate']
d['meta'].update(release=RELEASE,generated=DATE,release_digest_url='https://transduction.systems/updates/2026-10-07/',latest_intake_url='https://transduction.systems/updates/2026-10-07/',iteration_focus='Schot, complete recent SysCoI discovery intake, current events and public queue reconciliation',release_note='31 recent SysCoI reading leads; Schot source route; OrgLens; event and queue reconciliation.',node_count=len(d['nodes']),edge_count=len(d['edges']),source_count=len(d['sources']),profile_count=len(d['profiles']),public_entry_count=metrics['public_entries'],described_entry_count=metrics['public_entries'],reader_connected_entry_count=depth['reader_connected_entries'],semantic_connected_entry_count=depth['semantic_connected_entries'],unconnected_entry_count=depth['connection_bands'].get('unconnected',0),semantic_gap_entry_count=metrics['public_entries']-depth['semantic_connected_entries'],public_link_source_count=sum(s.get('public_link_status')=='public_link' for s in d['sources']),no_public_link_source_count=sum(s.get('public_link_status')=='no_public_link' for s in d['sources']))
for band in ['rich','developing','thin']:d['meta'][band+'_entry_count']=depth['connection_bands'].get(band,0)
for key in ['reading_list_inventory','reading_list_coverage','core_systems_practice']:d[key]['release']=RELEASE
d['ai_observations'].update(release=RELEASE,generated=DATE,metrics=metrics);upsert(d['ai_observations']['observations'],make_ai_observations(metrics)['observations'],'id')
observations_doc.RELEASE=RELEASE;observations_doc.GENERATED=DATE;observations_doc.write_ai_documentation(d)
write(d);q=quality_result(d);q.update(release=RELEASE,generated=DATE)
for key in ['adversarial_review','doncaster_lineage_review']:q[key]=d[key]
for path in ['data/relationship-quality.json','docs/assets/relationship-quality.json']:(ROOT/path).write_text(json.dumps(q,ensure_ascii=False,indent=2)+'\n')
write_relational_document(d)
css='body{margin:0;background:#faf8f2;color:#302b26;font:18px/1.65 Georgia,serif}main,nav,footer{max-width:62rem;margin:auto;padding:1.4rem}nav{display:flex;gap:1rem;flex-wrap:wrap;font:1rem/1.5 system-ui}a{color:#973d32;overflow-wrap:anywhere}a:focus-visible,summary:focus-visible{outline:3px solid #973d32;outline-offset:3px}h1{font-size:clamp(2.2rem,6vw,3.5rem);line-height:1.15}section,article{border-bottom:1px solid #d8d0c5;padding-bottom:1rem;margin-bottom:1.5rem}.meta{font:1rem/1.5 system-ui}summary{cursor:pointer;font-weight:bold}#openUpdates{position:fixed;bottom:0;right:0;width:44px;height:44px}#openUpdates:after{content:"";position:absolute;right:7px;bottom:7px;width:6px;height:6px;background:white;border-radius:50%;box-shadow:0 0 0 1px #777}@media(max-width:600px){main,nav,footer{padding:1rem}}'
def page(route,title,body):
    dest=DOCS/route.strip('/');dest.mkdir(parents=True,exist_ok=True)
    (dest/'index.html').write_text('<!doctype html><html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+E(title)+' | The Necessary Tangle</title><link rel="canonical" href="https://transduction.systems'+route+'"><style>'+css+'</style></head><body><nav aria-label="Main"><a href="/">Atlas</a><a href="/reading-list.html">Reading</a><a href="/events/">Events</a><a href="/updates/2026-10-07/">Latest update</a></nav><main><p class="meta">Release 0.30 · 7 October 2026</p><h1>'+E(title)+'</h1>'+body+'</main><footer><p>Curator: Benjamin P Taylor. Prepared with AI assistance. Source-scoped research remains open to review; editorial applications are labelled separately.</p></footer><a id="openUpdates" href="https://github.com/antlerboy/the-necessary-tangle/issues/2" aria-label="Open updates"></a></body></html>')
def atlas(nid,label):return '<a href="/#view=item&amp;id='+nid+'">'+E(label)+'</a>'
reader='<p>Johan Schot’s work asks how ways of meeting social needs change, and why similar directions of change recur across different socio-technical systems. Technology, institutions, markets, practices and infrastructure are considered together.</p><section id="distinctions"><h2>Three distinctions to keep</h2><p>The multi-level perspective examines interactions between innovation niches, established regimes and wider landscape pressures. These are analytical levels, not management ranks. A regime includes established rules and practices; it is more than the organisations currently delivering a service.</p><p>Deep Transitions extends the question across systems and longer historical periods. A rule can organise one system; a meta-rule is shared across systems; a meta-regime is a shared rule-set. The proposed sustainable Second Deep Transition is an ambition and research proposition, not an assured historical outcome.</p><p>A successful experiment and a changed regime are different achievements. Asking which rules select, fund and retain an innovation can sharpen inquiry, but does not remove questions of power, legitimacy or contested purpose.</p></section><section id="sources"><h2>Selected sources and locators</h2>'
for sid in [bio,guide,pathways,found,mlps,dts,policy]:
    s=next(x for x in d['sources'] if x['id']==sid);reader+='<article><h3><a href="'+E(s['url'])+'">'+E(s['title'])+'</a></h3><p>'+E(s['notes'])+'</p><p class="meta">'+E(s['source_locator'])+'</p></article>'
reader+='</section><section id="atlas"><h2>Inspect the atlas statements</h2><p>'+' · '.join(atlas(n,l) for n,l in [(schot,'Johan Schot'),(geels,'Frank Geels'),(kanger,'Laur Kanger'),(mlp,'Multi-level perspective'),(dt,'Deep Transitions'),(meta,'Meta-rules')])+'</p><p><a href="/#view=map&amp;focus='+dp+'&amp;layer=substantive&amp;depth=constellation&amp;edge=e30_found_meta">Inspect the source-located meta-rule distinction</a>. Graph statements are candidates with evidence locators; no generic influence or priority claim is added.</p></section><section id="application"><h2>Editorial application: why does a pilot stay exceptional?</h2><p>This public-service exercise is an original editorial application, not a case studied by Schot or a claim that his framework is proven in this setting.</p><p>A fictional relational service helps residents, but depends on temporary funding and staff bypassing ordinary rules. Compare two explanations: the surrounding rules prevent the practice becoming ordinary; or the practice works only under unusually favourable conditions.</p><ol><li>Name one rule: a budget condition, eligibility criterion, measure, professional boundary or decision right. How is it enforced? Who can change it?</li><li>Trace whether the same rule also shapes another service. A resemblance is a lead to test, not enough to establish a shared meta-rule.</li><li>Ask who defines success, whose experience is missing and who may challenge the purpose. Improvement inside a team can shift burdens onto residents.</li><li>Change one condition and observe whether the benefit survives without exceptional workarounds. Specify a result that would challenge your explanation.</li></ol><details><summary>Compare a possible response</summary><p>Track the resident’s benefit alongside the effort and exceptions needed to produce it. Test a revised funding or decision rule across two settings before treating it as a general explanation. Retain disagreement about the desired outcome. A historical theory can guide questions; it cannot grant authority to impose the answers.</p></details><p><a href="/systems-thinking/practice/critical-systems-heuristics/">Examine purposes, authority and affected people</a> · <a href="/systems-thinking/claim-lab/">Test a systems claim</a></p></section><section><h2>Previous SysCoI reading</h2>'
for url,label in [('https://stream.syscoi.com/2018/11/22/co-evolutionary-and-multi-level-dynamics-in-transitions-system-innovation-geels/','Co-evolutionary and multi-level dynamics'),('https://stream.syscoi.com/2022/08/12/the-dynamics-of-transitions-in-socio-technical-systems-a-multi-level-analysis-of-the-transition-pathway-from-horse-drawn-carriages-to-automobiles-1860-1930-geels-2006/','From horse-drawn carriages to automobiles'),('https://stream.syscoi.com/2019/06/25/leading-systems-change-nine-strategies-to-transform-the-way-the-world-works-forum-for-the-future/','Leading systems change: nine strategies')]:reader+='<p><a href="'+url+'">'+label+'</a></p>'
reader+='</section>';page('/reading/socio-technical-transitions/','Schot: socio-technical transitions and the conditions of change',reader)
digest='<p>This update includes all 31 published SysCoI additions found after 19 September through 7 October 2026, a source-led Schot reading, the current events collection and a review of newer public queue items. Reading leads, source-backed statements and editorial applications have different statuses.</p><p><a href="/reading/socio-technical-transitions/">Read Schot and test the conditions around a pilot</a> · '+atlas(tool,'OrgLens: experimental tool and evidence limits')+'</p><section id="recent"><h2>All recent SysCoI additions</h2><p>Titles, dates and outbound links were checked against the public posts. Inclusion records discovery; it does not certify all linked claims.</p>'
for r in P['posts']:
    digest+='<article id="post-'+str(r['id'])+'"><h3><a href="'+E(r['url'])+'">'+E(r['title'])+'</a></h3><p class="meta">'+r['date'][:10]+' · '+atlas('publication_syscoi_post_'+str(r['id']),'Atlas discovery record')+'</p>'
    if r['links']:digest+='<details><summary>Original links in this post</summary><ul>'+''.join('<li><a href="'+E(u)+'">'+E(u)+'</a></li>' for u in r['links'])+'</ul></details>'
    digest+='</article>'
digest+='</section><section id="events"><h2>Events and announcements</h2><p><a href="/events/">Explore the maintained worldwide map and calendar subscriptions</a>. Its current collection was refreshed on 7 October: 230 events, 130 upcoming, with 13 of 36 checked sources yielding dated events and seven reporting failures. These are collection figures, not a completeness claim.</p><p><a href="https://antlerboy.com/sysprac26/">Making relational, place-based public services ordinary</a>: Thursday 8 October, 12:30–14:00 UK time (Europe/London), online and free. The 30 September consulting workshop has taken place; its guide is linked from the organiser’s page. The cancelled conference appearance and the replacement online sessions are distinct records.</p><p>Myron Rogers’ workshop announcement remains undated. Direct inbox access returned HTTP 403, but the maintained workflow refreshed all four submissions. The Logosofia showcase is accepted for 21 October, 18:30–20:15 Toronto time, hybrid. Coding Society is a special issue announcement, classified as reading material. <a href="/events/submissions.html">Inspect public event submission status</a>.</p></section><section id="queue"><h2>Queued content: what changed and what remains</h2>'
for r in P['queue']:digest+='<article><h3>'+E(r['item'])+'</h3><p class="meta">'+E(r['status'])+'</p><p>'+E(r['result'])+'</p><p><a href="'+E(r['url'])+'">Open the source or result</a></p></article>'
digest+='</section><p><a href="review.json">Download the intake and queue record</a></p>';page('/updates/2026-10-07/','October intake: transitions, practice, tools and events',digest)
(DOCS/'updates/2026-10-07/review.json').write_text(json.dumps(P,ensure_ascii=False,indent=2)+'\n')
for route in ['reading-list.html','updates/index.html']:
    p=DOCS/route;t=p.read_text();t=re.sub('<!-- '+MARK+' -->.*?<!-- /'+MARK+' -->','',t,flags=re.S);t=t.replace('</main>','<!-- '+MARK+' --><section><h2>Latest intake: 7 October 2026</h2><p><a href="/updates/2026-10-07/">31 recent SysCoI additions, Schot, OrgLens, events and queue review</a> · <a href="/reading/socio-technical-transitions/">Read socio-technical transitions</a></p></section><!-- /'+MARK+' --></main>',1);p.write_text(t)
p=DOCS/'index.html';t=p.read_text()
t=re.sub(r'assets/public-data.js\?v=[^"\s]+','assets/public-data.js?v=0.30',t)
t=re.sub(r'<span id="releaseBadge">Release [^<]+</span>',f'<span id="releaseBadge">Release {RELEASE}</span>',t,count=1)
latest_note='<p class="release-note-inline"><strong>Updated for 0.30:</strong> 31 recent SysCoI discovery records, a source-led Johan Schot transitions reading route and exercise, OrgLens with explicit evidence limits, refreshed events, and transparent queue decisions. <a href="/updates/2026-10-07/">Inspect the dated intake and what remains open.</a></p>'
t=re.sub(r'<p class="release-note-inline"><strong>Updated for [^<]+:</strong>.*?</p>',latest_note,t,count=1,flags=re.S)
p.write_text(t)
p=DOCS/'sitemap.xml';t=p.read_text()
for route in ['/updates/2026-10-07/','/reading/socio-technical-transitions/']:
    if 'https://transduction.systems'+route not in t:t=t.replace('</urlset>','<url><loc>https://transduction.systems'+route+'</loc><lastmod>'+DATE+'</lastmod></url></urlset>')
t=re.sub(r'(<url><loc>https://transduction\.systems/</loc><lastmod>)[^<]+(</lastmod></url>)',r'\g<1>2026-10-08\2',t,count=1)
t=re.sub(r'<url><loc>https://transduction\.systems/events/</loc>(?:<lastmod>[^<]+</lastmod>)?</url>','<url><loc>https://transduction.systems/events/</loc><lastmod>'+DATE+'</lastmod></url>',t,count=1)
p.write_text(t)
p=ROOT/'CITATION.cff';t=p.read_text();t=re.sub(r'(?m)^version:.*$',"version: '0.30'",t);t=re.sub(r'(?m)^date-released:.*$',"date-released: '2026-10-07'",t);p.write_text(t)
print('Applied release 0.30: 31 discovery records, 7 transition statements, OrgLens and explicit queue dispositions.')

base=json.loads((ROOT/'sources/update-2026-10-07/base-state.json').read_text())
for name,text in base.items():
    entry="\n\n## Current release packet: 0.30, 7 October 2026\n\nAuthorised by the explicit user request to update The Necessary Tangle with Schot, all recent SysCoI additions, events and queued content. Source packet: sources/update-2026-10-07/PACKET.md. Includes all 31 posts after 19 September, source-located transition statements, OrgLens, a special-issue reading lead and four reviewed public event submissions. Events are pinned to the maintained 7 October collection. Bibliographic discovery is distinct from full-text and empirical review. The personal discussion informs a labelled original exercise; private notes are not published.\n\nAcceptance: make validate; focused mobile/desktop browser checks before deployment and on the live site; deployment.json identifies the release commit. Previous specialist, comparator reconciliation and full-text research remain queued. No access rights or invitations are changed. The source-owner-reviewed comparator is preserved.\n"
    at=text.find('\n');text=(text[:at]+entry+text[at:]) if text.startswith('# ') else entry.lstrip()+'\n'+text;(ROOT/'documentation'/name).write_text(text)

for name,heading,body in [('CHANGELOG.md','## 0.30 — 7 October 2026','Complete recent SysCoI discovery intake (31 posts), Schot transition sources and exercise, OrgLens with fictional-test limits, Coding Society special-issue lead, updated events and public queue dispositions. Historical source-title checks now distinguish quoted catalogue material from production framing while retaining full privacy and credential scans.'),('README.md','## Current intake: release 0.30','Read https://transduction.systems/updates/2026-10-07/ for the complete dated intake and queue decisions, and https://transduction.systems/reading/socio-technical-transitions/ for Schot sources and the labelled practice exercise. The maintained event snapshot includes 230 listings, 130 upcoming; source failures remain visible.')]:
    p=ROOT/name;t=p.read_text()
    if heading not in t:p.write_text(t.rstrip()+'\n\n'+heading+'\n\n'+body+'\n')
