"""Source-scoped reading, learning, map principles, and complete feedback disposition."""
from pathlib import Path
import html,json,re,math,hashlib
from apply_iteration_17 import enc,parse,upsert,source_record,node_record,profile_record,edge_record
from apply_iteration_09 import graph_metrics,make_ai_observations
from apply_relational_depth_16 import calculate_relational_depth,write_relational_document
from apply_doncaster_lineage import refresh_counts
from apply_overnight_review import quality_result
from refresh_graph_snapshot import calculate,write
import apply_iteration_10 as observations_doc
ROOT=Path(__file__).resolve().parents[1];DOCS=ROOT/'docs';MARK='update_20261008';DATE='2026-10-08';RELEASE='0.31'
P=json.loads((ROOT/'sources/update-2026-10-08/review.json').read_text())
d=json.loads((ROOT/'data/public-data.json').read_text());E=lambda x:html.escape(str(x),quote=True)
def source(sid,title,url,summary,creators=None,publisher='',year='2026',locator=''):
 r=source_record(sid,title,'public_source',url,summary,creators or [],publisher,year,quality='B')
 r.update(connection_pass=MARK,last_checked=DATE,review_status='source_scoped_research_pass',source_locator=locator)
 upsert(d['sources'],[r],'id');return sid
def node(nid,title,kind,summary,sids,tags=None):
 i=int(hashlib.sha256(nid.encode()).hexdigest()[:6],16)
 r=node_record(nid,title,kind,summary,sids,round(.55+.2*math.cos(i*2.4),6),round(.45+.2*math.sin(i*2.4),6),tags or [])
 r.update(connection_pass=MARK,status='candidate',review_status='research_pass_needs_editor',reviewed_by='',reviewed_at='',inclusion_reason=MARK,set_tags=enc(['systems','release_0_31',*(tags or [])]))
 upsert(d['nodes'],[r],'id');return nid
def edge(eid,a,b,typ,sid,locator,scope):
 family=next(r['relation_family'] for r in d['relation_types'] if r['relation_type']==typ)
 r=edge_record(eid,a,b,typ,family,typ.replace('_',' '),[sid],locator,scope,status='candidate',confidence='',review_label='Located source statement; curator review pending')
 vid='ev_'+eid;cid='claim_'+eid;r.update(connection_pass=MARK,evidence_ids=enc([vid]),claim_id=cid)
 upsert(d['edges'],[r],'id')
 upsert(d['evidence'],[dict(id=vid,source_id=sid,locator=locator,excerpt_or_summary=scope,evidence_type='located_public_source',quality_tier='B',licence='source terms',review_status='research_pass_needs_editor',content_hash='',public_evidence_status='public',connection_pass=MARK)],'id')
 upsert(d['claims'],[dict(id=cid,statement=scope,subject_id=a,predicate=typ,object_id=b,status='candidate',supporting_source_ids=enc([sid]),supporting_evidence_ids=enc([vid]),contradicting_source_ids='[]',contradicting_evidence_ids='[]',notes='Source-scoped interpretation. Human editorial acceptance remains pending.',review_status='research_pass_needs_editor',reviewed_by='',reviewed_at='',connection_pass=MARK)],'id')
def profile(nid,sids):
 n=next(n for n in d['nodes'] if n['id']==nid)
 r=profile_record(nid,n['description'],'Inspect the passage and the stated domain before using a term in a new setting.',['source account vs editorial interpretation','material exchange vs causal openness','bibliographic access vs full-text evidence'],[],[],[],['Name the domain, conditions, and observation that could challenge the proposed connection.'],['Treating a shared term as proof that two accounts are equivalent.'],['Original-source verification and human editorial review remain open.'],sids,editorial_note='AI-assisted source reading. Human curator: Benjamin P Taylor. New claims remain candidates.')
 r.update(connection_pass=MARK,title=n['label'],last_researched=DATE,review_status='research_pass_needs_editor',profile_status='evidence_deepened_research_pass');upsert(d['profiles'],[r],'node_id')
modules={m['id']:m for m in P['modules']}
for m in P['modules']:
 sid=source('src_u31_'+m['id'],m['title']+': researcher module',m['url'],'John A Challoner’s version 1 reconstruction, 30 September 2026. General and specialised definitions/propositions are labelled separately; original-author wording is not implied.',['John A Challoner'],'Rational Understanding',locator='Complete PDF, '+str(m['pages'])+' pages; specific claims carry page and proposition references')
 s=next(x for x in d['sources'] if x['id']==sid);s.update(content_hash=m['sha256'],source_role='secondary reconstruction',pages_read=m['pages'])
 node('publication_u31_'+m['id'],m['title']+' (Challoner, 2026)','publication',m['summary'],[sid],['researcher-modules'])
 if not any(n['id']==m['person'] for n in d['nodes']):
  name={'bhaskar':'Roy Bhaskar','bogdanov':'Alexander Bogdanov'}[m['id']]
  node(m['person'],name,'person','The '+name+' researcher module provides a secondary account of this thinker’s work. This entry establishes the reading route; it does not assign authorship of Challoner’s reconstruction to its subject.',[sid])
 edge('e31_subject_'+m['id'],'publication_u31_'+m['id'],m['person'],'presents_account_of',sid,'PDF p. 1: researcher and source basis','Challoner’s module presents this thinker’s work. Its reconstructions are secondary interpretations, not new direct testimony from the original author.')
for nid,title,summary,mid in P['new_concepts']:
 node(nid,title,'concept',summary,['src_u31_'+mid],['researcher-modules'])
for m in P['modules']:
 for i,(nid,locator,typ,scope) in enumerate(m['concepts']):
  edge('e31_module_'+m['id']+'_'+str(i+1),'publication_u31_'+m['id'],nid,typ,'src_u31_'+m['id'],locator,'In Challoner’s reconstruction: '+scope)
for i,(a,b,typ,mid,locator,scope) in enumerate(P['concept_edges']):
 edge('e31_concept_'+str(i+1),a,b,typ,'src_u31_'+mid,locator,'Source-scoped reading of Challoner’s module: '+scope)
for n in [n for n in d['nodes'] if n.get('connection_pass')==MARK]:profile(n['id'],parse(n['source_ids']))
ocadsource=source('src_u31_ocad_proforma','Understanding Systems: 2026 SFIN-6011 pro forma',P['ocad']['url'],'Complete twelve-module discussion pro forma read. Suggestions may not have entered the launched course. Module-linked works remain bibliographic leads unless separately reviewed.',['David Ing'],'Coevolving / OCAD',locator='Module_01 through Module_12; introductory status and CC BY notice')
ocadid='corpus_ing_ocad_reading_route_2026'
n=next(n for n in d['nodes'] if n['id']==ocadid)
n.update(description='David Ing’s published 2026 Understanding Systems pro forma, now available through a twelve-module reading guide. It proposes an inquiry through design, feedback, soft systems, ecological complexity, boundary critique, and synthesis. It is a discussion document rather than proof of the launched curriculum.',source_ids=enc(sorted(set(parse(n['source_ids'])+[ocadsource]))))
for x in d['profiles']:
 if x['node_id']==ocadid:x.update(definition=n['description'],source_ids=n['source_ids'])
for nid,number in P['ocad']['method_links']:
 edge('e31_ocad_'+str(number)+'_'+nid,nid,ocadid,'taught_in',ocadsource,'Module_'+str(number).zfill(2),'Included as a proposed teaching topic in this published pro forma. This does not establish delivery, enrolment availability, or endorsement of every associated claim.')
issssource=source('src_u31_isss_students','ISSS education resources',P['isss']['url'],'Student-facing tools, training leads, and 57 bibliographic entries transcribed into seven source categories. Full-text reading of the listed works is not claimed.',[],'ISSS',locator='Systems Modeling Software; Courses; Readings to Get Started')
isssid=node('collection_isss_students_2026','ISSS student reading and resource guide','collection','A source-located guide to the ISSS student resource page: software, training leads, and 57 bibliography entries in seven categories. The collection leans towards modelling; it is one route through systems sciences, not a complete field boundary.',[issssource])
profile(isssid,[issssource])
# Editorial cross-routes are navigation, not source-asserted graph relationships.
orgsource=source('src_u31_orglens_article','OrgLens 2: making an organisational health check people can actually use','https://substrate.dougbelshaw.com/orglens-2-making-an-organisational-health-check-people-can-actually-use','Maintainer report of an experimental pipeline, evidence checks, and plain-language reports. Three fictional cases and simulated readers are not independent field evaluation.',['Doug Belshaw'],'Doug Belshaw',locator='Checking claims; From agent to web app; Limitations')
orgnode=next(n for n in d['nodes'] if n['id']=='tool_orglens');orgnode['source_ids']=enc(sorted(set(parse(orgnode['source_ids'])+[orgsource])))
ssm='method_or_methodology_soft_systems_methodology_ssm';csh='method_or_methodology_critical_systems_heuristics_csh'
for nid in [ssm,csh]:edge('e31_orglens_'+nid,'tool_orglens',nid,'uses','src_u30_orglens','README: perspectives and boundaries lens','The maintainer describes SSM and CSH as resources for a lens on perspectives and boundaries. This records the claimed design, not demonstrated organisational effectiveness.')
d[MARK]=dict(release=RELEASE,reader_url='/updates/2026-10-08/',comments=len(P['comments']),open_issues=len(P['issues']),researcher_pdf_pages=sum(m['pages'] for m in P['modules']),isss_bibliographic_entries=len(P['isss']['readings']))
refresh_counts(d);d['relational_depth']=calculate_relational_depth(d);d['relational_depth'].update(release=RELEASE,generated=DATE);d['graph_snapshot']=calculate(d);metrics=graph_metrics(d);depth=d['relational_depth']['aggregate']
d['meta'].update(release=RELEASE,generated=DATE,release_digest_url='https://transduction.systems/updates/2026-10-08/',latest_intake_url='https://transduction.systems/updates/2026-10-08/',iteration_focus='Full feedback disposition, reliable map navigation, learning routes, and source-scoped conceptual reading',release_note='Map refocus and links repaired; learning directory; OCAD and ISSS guides; five researcher modules; map principles and complete feedback review.',node_count=len(d['nodes']),edge_count=len(d['edges']),source_count=len(d['sources']),profile_count=len(d['profiles']),public_entry_count=metrics['public_entries'],described_entry_count=metrics['public_entries'],reader_connected_entry_count=depth['reader_connected_entries'],semantic_connected_entry_count=depth['semantic_connected_entries'],unconnected_entry_count=depth['connection_bands'].get('unconnected',0),semantic_gap_entry_count=metrics['public_entries']-depth['semantic_connected_entries'],public_link_source_count=sum(s.get('public_link_status')=='public_link' for s in d['sources']),no_public_link_source_count=sum(s.get('public_link_status')=='no_public_link' for s in d['sources']))
for band in ['rich','developing','thin']:d['meta'][band+'_entry_count']=depth['connection_bands'].get(band,0)
for key in ['reading_list_inventory','reading_list_coverage','core_systems_practice']:d[key]['release']=RELEASE
d['ai_observations'].update(release=RELEASE,generated=DATE,metrics=metrics);upsert(d['ai_observations']['observations'],make_ai_observations(metrics)['observations'],'id')
upsert(d['ai_observations']['observations'],[dict(id='observation_source_depth_31',title='Access, reading, and review are different forms of progress',kind='editorial observation',measurement='This pass read 5 complete researcher PDFs (32 pages), the 12-module OCAD pro forma, and the ISSS resource list (57 bibliographic entries). All 85 notebook comments and 14 open issues have a disposition.',interpretation='A longer bibliography increases discoverability. It does not show that the works have been read or that the claims have received human review. New graph claims retain candidate status.',implication='Prioritise primary-source verification and human review where a new distinction affects practice. Do not use link or node counts as a proxy for confidence.',test='Sample the new claims against their page locators; ask a human editor to accept, qualify, or reject them. Check whether a reader can distinguish original text, secondary reconstruction, and editorial application.')],'id')
observations_doc.RELEASE=RELEASE;observations_doc.GENERATED=DATE;observations_doc.write_ai_documentation(d)
write(d);q=quality_result(d);q.update(release=RELEASE,generated=DATE)
for key in ['adversarial_review','doncaster_lineage_review']:q[key]=d[key]
for path in ['data/relationship-quality.json','docs/assets/relationship-quality.json']:(ROOT/path).write_text(json.dumps(q,ensure_ascii=False,indent=2)+'\n')
write_relational_document(d)
css=':root{color-scheme:light}*{box-sizing:border-box}body{margin:0;background:#faf8f2;color:#302b26;font:18px/1.65 Georgia,serif}main,nav,footer{max-width:68rem;margin:auto;padding:1.4rem}nav{display:flex;gap:1rem;flex-wrap:wrap;font:1rem/1.5 system-ui}a{color:#973d32;overflow-wrap:anywhere}a:focus-visible,summary:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid #973d32;outline-offset:3px}h1{font-size:clamp(2.1rem,6vw,3.6rem);line-height:1.15;max-width:24ch}h2{line-height:1.3}section,article{border-bottom:1px solid #d8d0c5;padding-bottom:1rem;margin-bottom:1.5rem}.meta,.status,label{font:1rem/1.5 system-ui}.status{color:#63574a}summary{cursor:pointer;font-weight:bold;padding:.5rem 0}input,select{font:inherit;max-width:100%;padding:.45rem;border:1px solid #938779;background:#fffdf7}label{display:grid;gap:.4rem}.filters{display:flex;flex-wrap:wrap;gap:1rem;padding:1rem 0}.filters label:first-child{flex:1;min-width:12rem}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,27rem),1fr));gap:1.4rem}.grid article{padding:1.1rem;border:1px solid #d8d0c5;border-top:3px solid #973d32;margin:0}table{border-collapse:collapse;width:100%;font-size:.94rem}th,td{padding:.65rem;vertical-align:top;border-bottom:1px solid #d8d0c5;text-align:left;overflow-wrap:anywhere}.table-wrap{overflow:auto}blockquote{border-left:3px solid #973d32;margin-left:0;padding-left:1rem}.note{background:#f0eadd;padding:1rem}#openUpdates{position:fixed;bottom:0;right:0;width:44px;height:44px}#openUpdates:after{content:"";position:absolute;right:8px;bottom:8px;width:5px;height:5px;background:#862719;border-radius:50%;box-shadow:0 0 0 1px #fff}[hidden]{display:none!important}@media(max-width:600px){main,nav,footer{padding:1rem}ul,ol{padding-left:1.35rem}td,th{padding:.5rem}.table-wrap table{min-width:38rem}}'
routes=[]
def page(route,title,body,script=''):
 dest=DOCS/route.strip('/');dest.mkdir(parents=True,exist_ok=True);routes.append(route)
 (dest/'index.html').write_text('<!doctype html><html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+E(title)+' | The Necessary Tangle</title><link rel="canonical" href="https://transduction.systems'+route+'"><style>'+css+'</style></head><body><nav aria-label="Main"><a href="/">Atlas</a><a href="/learning/">Learning</a><a href="/reading-list.html">Reading</a><a href="/prior-maps/principles/">Map principles</a><a href="/updates/2026-10-08/">Latest update</a></nav><main><p class="meta">Release 0.31 · 8 October 2026</p><h1>'+E(title)+'</h1>'+body+'</main><footer><p>Curator: Benjamin P Taylor. Prepared with AI assistance. Source-scoped research remains open to human review; editorial applications are labelled separately.</p><p><a href="/#view=contribute">Suggest a correction by email or public issue</a>.</p></footer><a id="openUpdates" href="https://github.com/antlerboy/the-necessary-tangle/issues/2" aria-label="Open updates"></a>'+script+'</body></html>')
def link(url,title):return '<a href="'+E(url)+'">'+E(title)+'</a>'
def atlas(nid,title):return link('/#view=item&id='+nid,title)
def details(title,body):return '<details><summary>'+E(title)+'</summary>'+body+'</details>'
body='<p>Start with the question you need to explore, then choose a learning setting. This directory brings together open materials, courses, programmes, society resources, and the atlas’s own practice routes.</p><p class="note">Access labels describe the listed route, not every resource or qualification offered by a provider. Provider pages determine current dates, fees, and admission. Benjamin P Taylor has professional roles at RedQuadrant and PSTA.</p><div class="filters"><label>Find a learning route<input id="learningSearch" type="search" placeholder="Provider, method, or topic"></label><label>Access<select id="learningAccess"><option value="">All access types</option><option value="open">Open or free routes</option><option value="provider">Provider terms</option><option value="mixed">Mixed access</option></select></label></div><p id="learningCount" role="status"></p><div class="grid" id="learningRoutes">'
for r in P['training']:
 access='open' if any(x in r['access'].lower() for x in ['open','free']) else 'mixed' if r['access']=='Mixed access' else 'provider'
 body+='<article data-access="'+access+'"><p class="meta">'+E(r['provider'])+' · '+E(r['format'])+'</p><h2>'+link(r['url'],r['title'])+'</h2><p>'+E(r['summary'])+'</p><p class="status">'+E(r['access'])+' · checked '+r['checked']+'</p></article>'
body+='</div><section><h2>Find a live gathering</h2><p>'+link('/events/','Events, society meetings, and calendar subscriptions')+'. The learning directory holds enduring routes; the events collection holds dated listings.</p></section>'
script='''<script>(()=>{const q=document.getElementById('learningSearch'),a=document.getElementById('learningAccess'),cards=[...document.querySelectorAll('#learningRoutes article')];const sp=new URLSearchParams(location.search);q.value=sp.get('q')||'';a.value=sp.get('access')||'';function filter(write){const term=q.value.trim().toLowerCase();let n=0;for(const c of cards){c.hidden=!(c.textContent.toLowerCase().includes(term)&&(!a.value||c.dataset.access===a.value));if(!c.hidden)n++;}document.getElementById('learningCount').textContent=n+' of '+cards.length+' learning routes';if(write){const p=new URLSearchParams();if(q.value)p.set('q',q.value);if(a.value)p.set('access',a.value);history.replaceState(null,'',location.pathname+(p.size?'?'+p:''));}}q.addEventListener('input',()=>filter(true));a.addEventListener('change',()=>filter(true));filter(false);})();</script>'''
page('/learning/','Learning and training',body,script)
body='<p>David Ing’s '+link(P['ocad']['url'],'complete 2026 Understanding Systems pro forma')+' is now available to read. It connects systems inquiry, design, visualisation, and collective learning across twelve modules.</p><p class="note">'+E(P['ocad']['status'])+' The pro forma is published under CC BY by David Ing. The headings, short guides, and inquiry prompts below are editorial aids. Links identify works in the pro forma; inclusion does not mean the atlas has read every linked work.</p><p>'+link('#module-1','Start with module 1')+' · '+link('/learning/isss/','Compare the ISSS modelling bibliography')+' · '+atlas(ocadid,'Inspect the atlas reading-route record')+'</p>'
for m in P['ocad']['modules']:
 body+='<section id="module-'+str(m['number'])+'"><p class="meta">Module '+str(m['number'])+'</p><h2>'+E(m['title'])+'</h2><p>'+E(m['summary'])+'</p><p>'+link(m['source_url'],'Read the corresponding source module')+'</p><p><strong>Editorial inquiry:</strong> '+E(m['exercise'])+'</p>'+details(str(len(m['links']))+' source links in this module','<ul>'+''.join('<li>'+link(l['url'],l['title'] or l['url'])+'</li>' for l in m['links'])+'</ul>')+'</section>'
body+='<section><h2>Read across the course</h2><p>Keep a small record of an inquiry: the situation, your boundary, the people whose accounts differ, the relations you propose, and the observations that might change them. Revisit that record as the methods change. This is an editorial exercise; it is not a claimed course assessment.</p><p>The source’s final section is a placeholder, so this guide adds no final-assessment requirements.</p></section>'
page('/corpora/ing-ocad/','Understanding Systems: a twelve-module reading guide',body)
body='<p>The '+link(P['isss']['url'],'ISSS student resource page')+' is a useful entry into modelling, with software, training leads, and a bibliography spanning several method families. Its emphasis does not define the whole of systems sciences.</p><p class="note">'+E(P['isss']['status'])+' The 57 rows below retain the source’s bibliographic statements, including edition variants. A title appearing twice is not silently treated as two distinct works.</p><section><h2>Choose a route through the sources</h2><p>For feedback over time, start with system dynamics. For heterogeneous actors and local interactions, inspect agent-based models. For relational structure, inspect network methods. Then ask what each representation leaves outside its boundary.</p><p>Compare these modelling routes with '+link('/corpora/ing-ocad/','Ing’s design and inquiry route')+', '+link('/systems-thinking/practice/','the practice laboratory')+', and '+link('/systems-sciences/','the Systems Sciences stewardship page')+'. This comparison is editorial guidance rather than a recommendation attributed to ISSS.</p></section><section><h2>Tools and training leads</h2><p>These are links listed by ISSS. Historical dates, software editions, and access conditions need checking at the destination.</p><ul>'
seen=set()
for r in P['isss']['resources']:
 if r['url'] in seen:continue
 seen.add(r['url']);body+='<li>'+link(r['url'],r['title'] or r['url'])+'</li>'
body+='</ul></section>'
for category in dict.fromkeys(r['category'] for r in P['isss']['readings']):
 rows=[r for r in P['isss']['readings'] if r['category']==category]
 body+='<section><h2>'+E(category)+'</h2><ol>'+''.join('<li>'+E(r['citation'])+(' '+ ' · '.join(link(u,'Source-listed link') for u in r['links']) if r['links'] else '')+'</li>' for r in rows)+'</ol></section>'
body+='<section><h2>Beyond the student list</h2><p>The '+link('https://www.isss.org/home/','ISSS home resource hub')+' links proceedings, a primer, the wiki, and contributed maps and learning accounts. Follow those as separately authored collections.</p><ul>'+''.join('<li>'+link(u,t)+'</li>' for u,t in [('https://journals.isss.org/','ISSS proceedings'),('https://web3.isss.org/primer2/','ISSS primer'),('https://wiki.isss.org/','ISSS wiki'),('https://web3.isss.org/marzolf-aug2023/index.html','Tom Marzolf’s systems learning material'),('https://desc.systems/','Bruce McNaughton’s systems descriptions')])+'</ul></section>'
page('/learning/isss/','ISSS: routes into systems sciences',body)
body='<p>John A Challoner’s '+link('https://rational-understanding.com/researchers/','Rational Understanding researcher modules')+' translate five bodies of work into a common arrangement of definitions and propositions. All five PDFs were read for this guide: 32 pages in total.</p><p class="note">These are secondary reconstructions, version 1 dated 30 September 2026. DG and PG label general definitions and propositions; DS and PS label specialised ones. The modules distinguish explicit claims from reconstructions. Their common format does not prove that the thinkers used the same concepts, and an ISSS header is not by itself evidence of institutional endorsement.</p>'
for m in P['modules']:
 body+='<section id="'+m['id']+'"><h2>'+E(m['title'])+'</h2><p>'+E(m['summary'])+'</p><p><strong>Keep the distinction:</strong> '+E(m['distinction'])+'</p><p>'+link(m['url'],'Read the '+str(m['pages'])+'-page module')+' · '+atlas('publication_u31_'+m['id'],'Inspect the atlas statements')+'</p><ul>'
 for nid,locator,typ,scope in m['concepts']:
  n=next(n for n in d['nodes'] if n['id']==nid);body+='<li>'+atlas(nid,n['label'])+': '+E(locator)+'.</li>'
 body+='</ul></section>'
body+='<section><h2>Compare without collapsing meanings</h2><p>Material openness, energy exchange, and causal openness answer different questions. A system can exchange energy without exchanging matter. Equifinality is conditional; a dissipative structure is not simply anything that changes; organisation can concern relations without supplying a universal management prescription.</p><p><strong>Editorial exercise:</strong> take a proposed organisational claim containing one of these terms. Identify the source proposition, its domain, and the additional argument needed for transfer. Write an observation that would count against that transfer.</p><p>'+link('https://ashby.info/','Read Ashby’s original archive')+'. Original-source checks for the other modules remain part of the research queue; the secondary reading is not reported as their completion.</p></section>'
page('/reading/researcher-modules/','Five researchers, with their distinctions intact',body)
body='<p>Doug Belshaw’s '+link('https://substrate.dougbelshaw.com/orglens-2-making-an-organisational-health-check-people-can-actually-use','second OrgLens development account')+' describes moving from an agent-driven experiment to a fixed reporting pipeline.</p><p>The reported design separates structural checks from model-generated writing. It checks quotations against notes, tests for contradictions, and moves specialist terminology out of the main report. These are claims about the experimental design and its tests.</p><p>The cases were fictional and the readers were simulated. The same AI setup contributed to construction and evaluation, with small samples. Report clarity under those conditions does not establish whether diagnoses are fair or useful to people in a real organisation.</p><p>'+atlas('tool_orglens','Inspect OrgLens and its claimed systems lenses')+' · '+link('https://framagit.org/dynamicskillset/orglens','Read the maintained source repository')+'</p><section><h2>Editorial application: inspect the evidence chain</h2><ol><li>Can a reader trace each claim to the submitted account?</li><li>Does a structural check test the claim, or only the consistency of its representation?</li><li>Can the people described dispute the interpretation and decide what happens next?</li></ol><p>A readable report can still encode a weak or inappropriate model. Human review must address the interpretation as well as the quotations.</p></section>'
page('/reading/orglens/','OrgLens: readable reports and the limits of their evidence',body)
body='<p>A systems map makes selections: what matters, what belongs together, what came before, and what a connection means. The Necessary Tangle treats those selections as claims that readers should be able to inspect and challenge.</p>'
for title,text in P['principles']:body+='<section><h2>'+E(title)+'</h2><p>'+E(text)+'</p></section>'
body+='<section><h2>Sources for these editorial principles</h2><p>These principles are the atlas’s editorial commitments, informed by the following discussions. They do not adopt every historical judgement made in those sources.</p><ul>'+''.join('<li>'+link(r['url'],r['title'])+'</li>' for r in P['principle_sources'])+'</ul><p>'+link('/prior-maps/review-2026-10/','Inspect the inheritance and its unresolved questions')+' · '+link('/#view=map','Explore the map')+'</p></section>'
page('/prior-maps/principles/','Principles for a revisable map',body)
audit=json.loads((ROOT/'sources/update-2026-10-08/castellani-link-audit.json').read_text())
counts={}
for x in audit['links']:counts[x['reachability']]=counts.get(x['reachability'],0)+1
body='<p>The inheritance contains different kinds of map: historical arguments, visual teaching accounts, explicit source networks, and bibliometric signals. A common drawing style is not evidence that their lines mean the same thing.</p><p class="note">This review identifies the public works and the available source texts. Text search did not establish a complete inventory of image-only files. Private storage details and source files are not republished.</p>'
for title,author,url,status,nextstep in P['maps']:
 body+='<article><h2>'+(link(url,title) if url else E(title))+'</h2><p class="meta">'+E(author)+'</p><p>'+E(status)+'</p><p><strong>Next evidence:</strong> '+E(nextstep)+'</p></article>'
body+='<section id="castellani-audit"><h2>All 307 Castellani destinations checked</h2><p>'+E('; '.join(str(v)+' '+k.lower() for k,v in counts.items()))+'. These results describe this check, not permanent availability or semantic correctness. Source labels and comparator bytes remain unchanged.</p><p>'+link('castellani-link-audit.json','Download the complete dated audit')+'</p>'+details('Inspect the 28 source label disagreements','<ul>'+''.join('<li>'+E(x['alt'])+' / '+E(x['title'])+' — '+link(x['href'],x['display_label'])+'; '+E(x['reachability'])+'</li>' for x in audit['links'] if x['label_disagreement'])+'</ul>')+'</section><p>'+link('/prior-maps/principles/','Read the map principles')+' · '+link('/updates/2026-10-08/#actions','Inspect the remaining action programme')+'</p>'
page('/prior-maps/review-2026-10/','Reading the inheritance: map review, October 2026',body)
(DOCS/'prior-maps/review-2026-10/castellani-link-audit.json').write_text(json.dumps(audit,ensure_ascii=False,indent=2)+'\n')
body='<p>This release reviews all 85 comments in the update notebook and all 14 open issues present at the start of the pass. It repairs map navigation, adds a learning home, deepens named source routes, and publishes explicit map principles. The ledger distinguishes delivered changes from continuing research and human decisions.</p><ul>'+''.join('<li>'+link(u,t)+'</li>' for u,t in [('/learning/','Learning and training directory'),('/corpora/ing-ocad/','Twelve-module Understanding Systems guide'),('/learning/isss/','ISSS bibliography and learning resources'),('/reading/researcher-modules/','Five researcher modules: 32 pages read'),('/reading/orglens/','OrgLens development account'),('/prior-maps/principles/','Map principles'),('/prior-maps/review-2026-10/','Map inheritance and 307-destination audit')])+'</ul><section><h2>Map changes</h2><p>Refocusing keeps the selected layer, family, and scale. Graph and card views have shareable links. Selecting an edge records it in the URL. Links support opening in another tab. Path mode alone returns to one-step neighbours when a new centre makes the old path inapplicable.</p></section><section id="actions"><h2>Action dispositions</h2>'
for a in P['actions']:body+='<article id="action-'+a['id']+'"><h3>'+E(a['title'])+'</h3><p class="status">'+E(a['status'])+'</p><p>'+E(a['result'])+'</p><p>'+link(a['url'],'Inspect the result or current route')+'</p></article>'
body+='</section><section id="issues"><h2>All open issues</h2><p>These issues remain open where their completion criteria exceed this release. They are not closed merely because they appear in this review.</p>'
for r in sorted(P['issues'],key=lambda x:x['number']):body+='<article><h3>'+link(r['url'],'#'+str(r['number'])+': '+r['title'])+'</h3><p>'+E(r['next'])+'</p></article>'
body+='</section><section id="comments"><h2>Every notebook comment</h2><p>Each numbered row refers to one original comment, in chronological order. Several comments share actions; release reports are identified as history.</p><ol>'
for c in P['comments']:body+='<li id="comment-'+str(c['id'])+'">'+link(c['url'],'Original comment '+str(c['number']))+': '+', '.join(link('#action-'+aid,next(a['title'] for a in P['actions'] if a['id']==aid)) for aid in c['actions'])+'.</li>'
body+='</ol></section><p>'+link('review.json','Download the complete review and source packet')+' · '+link('/#view=ai-observations','Inspect updated AI-assisted observations')+'</p>'
page('/updates/2026-10-08/','Full feedback review: what changed and what remains',body)
(DOCS/'updates/2026-10-08/review.json').write_text(json.dumps(P,ensure_ascii=False,indent=2)+'\n')
for route in ['reading-list.html','updates/index.html','prior-maps/index.html']:
 p=DOCS/route;t=p.read_text();t=re.sub('<!-- '+MARK+' -->.*?<!-- /'+MARK+' -->','',t,flags=re.S);t=t.replace('</main>','<!-- '+MARK+' --><section><h2>Update: 8 October 2026</h2><p>'+link('/updates/2026-10-08/','Full feedback review')+' · '+link('/learning/','Learning and training')+' · '+link('/reading/researcher-modules/','Five researcher modules')+' · '+link('/prior-maps/principles/','Map principles')+'</p></section><!-- /'+MARK+' --></main>',1);p.write_text(t)
p=DOCS/'index.html';t=p.read_text();t=re.sub(r'assets/public-data.js\?v=[^"\s]+','assets/public-data.js?v=0.31',t);t=re.sub(r'<span id="releaseBadge">Release [^<]+</span>',f'<span id="releaseBadge">Release {RELEASE}</span>',t,count=1)
t=re.sub(r'<p class="release-note-inline"><strong>Updated for [^<]+:</strong>.*?</p>','<p class="release-note-inline"><strong>Updated for 0.31:</strong> reliable map refocus and shareable views, a learning directory, source-led OCAD and ISSS routes, five researcher modules, and a complete feedback review. '+link('/updates/2026-10-08/','Read the changes and remaining work')+'.</p>',t,count=1,flags=re.S)
t=re.sub('<!-- learning-nav-31 -->.*?<!-- /learning-nav-31 -->','',t,flags=re.S)
t=t.replace('<nav class="main-nav"','<nav class="main-nav"',1)
match=re.search(r'(<nav\b[^>]*class="[^"]*main-nav[^"]*"[^>]*>)(.*?)(</nav>)',t,re.S)
if match:t=t[:match.end(2)]+'<!-- learning-nav-31 --><a href="/learning/">Learning</a><!-- /learning-nav-31 -->'+t[match.end(2):]
p.write_text(t)
p=DOCS/'sitemap.xml';t=p.read_text()
for route in routes:
 if 'https://transduction.systems'+route+'</loc>' not in t:t=t.replace('</urlset>','<url><loc>https://transduction.systems'+route+'</loc><lastmod>'+DATE+'</lastmod></url></urlset>')
p.write_text(t)
p=ROOT/'CITATION.cff';t=p.read_text();t=re.sub(r'(?m)^version:.*$',"version: '0.31'",t);t=re.sub(r'(?m)^date-released:.*$',"date-released: '2026-10-08'",t);p.write_text(t)
entry='## 0.31 — 8 October 2026\n\nMap refocus, modified clicks, edge selection, and shareable card views repaired. Dedicated learning directory, twelve-module OCAD guide, ISSS bibliography (57 entries), five complete researcher-module readings (32 pages), OrgLens follow-up, map principles, and a 307-destination comparator audit. All 85 notebook comments and 14 open issues have explicit dispositions. New graph statements remain candidates with sources, locators, and scope.\n'
p=ROOT/'CHANGELOG.md';t=p.read_text()
if '## 0.31 ' not in t:p.write_text(t.rstrip()+'\n\n'+entry)
p=ROOT/'README.md';t=p.read_text();t=re.sub(r'\n*<!-- current-31 -->.*?<!-- /current-31 -->\n*','\n\n',t,flags=re.S);at=t.find('\n');t=t[:at+1]+'\n<!-- current-31 -->\nCurrent release: **0.31, 8 October 2026**. [Read the complete update](https://transduction.systems/updates/2026-10-08/), [learning directory](https://transduction.systems/learning/), and [remaining work](https://transduction.systems/updates/2026-10-08/#issues).\n<!-- /current-31 -->\n'+t[at+1:].lstrip('\n');p.write_text(t)
(ROOT/'documentation/TANGLE_STATE.md').write_text('# Current Tangle state\n\nLast verified: 8 October 2026 (release build; deployment verification is recorded by deployment.json and CI).\n\nPublic site: https://transduction.systems/\n\nRelease 0.31. '+str(metrics['public_entries'])+' public entries, '+str(len(d['edges']))+' recorded edges, '+str(len(d['sources']))+' sources, and '+str(len(d['profiles']))+' profiles. Counts describe the dataset, not universal coverage or human acceptance. Machine quality snapshot: data/relationship-quality.json.\n\nThe current source packet is sources/update-2026-10-08/PACKET.md and review.json. It accounts for all 85 update-notebook comments and 14 open issues at the start of the pass. The public result is /updates/2026-10-08/. New graph statements are source-located candidates awaiting human editorial decisions. The source-owner-reviewed Systemic Evolution comparator remains unchanged.\n\nMap links preserve focus settings and representation. Learning has a dedicated /learning/ home. The OCAD pro forma, ISSS bibliography, five researcher PDFs, OrgLens follow-up, map principles, and comparator reachability audit have dedicated routes. Full primary-source review of all corpora, image-only inventory, independent comparator reconciliation, and disputed submissions remain open.\n\nHuman curator: Benjamin P Taylor. No membership, permissions, invitations, or external correspondence changed. Previous release records remain in CHANGELOG.md and their source packets.\n')
(ROOT/'documentation/NEXT_WORK.md').write_text('# Next work\n\nStatus: release 0.31 implementation complete. Publication is confirmed by deployment.json and live checks; no continuing research packet is automatically active.\n\n## Outcome\n\nPublish the authorised full feedback update and verify the deployed commit. Source packet: sources/update-2026-10-08/PACKET.md.\n\n## In scope\n\nRun the full gate and focused desktop/mobile reader checks; resolve named failures; publish and verify the live release. The public issue and comment ledger records completed and continuing work.\n\n## Out of scope\n\nDo not manufacture completion of corpus reading, human review, source-owner approval, or unverified comparator equivalence. Do not change access rights or send invitations.\n\n## Acceptance checks\n\nmake validate; scripts/test_update_31_browser.js; preserved comparator hashes; live deployment.json and changed reader routes.\n\n## Stop conditions\n\nStop when the accepted release is published and its live reader checks pass. Continuing research needs a finite source cohort and explicit completion criteria, listed in /updates/2026-10-08/#issues.\n\n## Model route\n\nNo delegated agents for this packet. Source reading and build are separate records; AI-assisted claims retain human review requirements.\n')
print('Applied 0.31:',sum(n.get('connection_pass')==MARK for n in d['nodes']),'new entries;',sum(e.get('connection_pass')==MARK for e in d['edges']),'located candidate statements; 85 comment dispositions.')
