"""Four source-located statements on existing entities, and a reader comparison."""
from pathlib import Path
import html,json,re
from apply_iteration_17 import source_record,edge_record,profile_record,enc,parse,upsert
from apply_iteration_09 import graph_metrics,make_ai_observations
from apply_relational_depth_16 import calculate_relational_depth,write_relational_document
from apply_doncaster_lineage import refresh_counts
from apply_overnight_review import quality_result
from refresh_graph_snapshot import calculate,write
ROOT=Path(__file__).resolve().parents[1];DOCS=ROOT/'docs';DATE='2026-10-04';RELEASE='0.29';MARK='weaver_20261004'
P=json.loads((ROOT/'sources/weaver-2026-10-04/review.json').read_text(encoding='utf-8'))
SID='src_weaver_complexity_transcription_1948';PUB='publication_fpcs_010';ROUTE='/reading/weaver-complexity/'
d=json.loads((ROOT/'data/public-data.json').read_text(encoding='utf-8'));nodes={n['id']:n for n in d['nodes']};types={r['relation_type']:r for r in d['relation_types']}
source=source_record(SID,'Science and Complexity: selected passages in a later transcription','primary_text_transcription',P['source']['access_url'],P['source']['representation']+' '+P['source']['review_scope']+' '+P['source']['integrity_note'],['Warren Weaver'],'Original: American Scientist; later transcription hosted by Architexturez','1948',quality='B')
source.update(connection_pass=MARK,last_checked=DATE,review_status='selected_passages_checked_transcription_not_facsimile',access='public_full_text',public_link_status='public_link')
upsert(d['sources'],[source],'id')
for c in P['claims']:
    assert c['target_id'] in nodes and c['relation_type'] in types
    eid='e29_'+c['id'].replace('-','_');vid='ev29_'+c['id'];cid='claim29_'+c['id']
    scope=c['reader_statement']+' Source account only; contemporary organisational applications are editorial. Later transcription, not original journal pagination.'
    e=edge_record(eid,PUB,c['target_id'],c['relation_type'],c['relation_family'],c['plain_phrase'],[SID],c['locator'],scope,status='candidate',confidence='',review_label='Source passage located; curator review pending')
    e.update(connection_pass=MARK,evidence_ids=enc([vid]),claim_id=cid,reviewed_by='',reviewed_at='')
    upsert(d['edges'],[e],'id')
    upsert(d['evidence'],[dict(id=vid,source_id=SID,locator=c['locator'],excerpt_or_summary=c['reader_statement'],evidence_type='located_primary_text_transcription',quality_tier='B',licence='see_source',review_status='research_pass_needs_editor',content_hash='',public_evidence_status='public',connection_pass=MARK)],'id')
    upsert(d['claims'],[dict(id=cid,statement=c['reader_statement'],subject_id=PUB,predicate=c['relation_type'],object_id=c['target_id'],status='candidate',supporting_source_ids=enc([SID]),supporting_evidence_ids=enc([vid]),contradicting_source_ids='[]',contradicting_evidence_ids='[]',notes='Selected passage of a later transcription. Curator review pending; no original-edition or lineage claim.',review_status='research_pass_needs_editor',reviewed_by='',reviewed_at='',connection_pass=MARK)],'id')
summary='Weaver’s 1948 essay distinguishes kinds of scientific problem and examines both the promise and limits of scientific inquiry. Selected passages have been read in a later transcription; the original journal text and pagination have not been checked.'
node=nodes[PUB];node.update(reviewed_by='',reviewed_at='',description=summary,canonical_definition=summary,publication_level='profile',public_stub_text='',review_status='selected_passages_checked_transcription_not_facsimile',source_ids=enc(list(dict.fromkeys(parse(node['source_ids'])+[SID]))))
profile=profile_record(PUB,summary,'Use the source to question a methodological choice, rather than treating a historical classification as a universal sorting rule.',['source text vs organisational application','transcription page vs original journal page'],[],[],[],['State what the model must explain and which observations could challenge it.'],[],['Compare the transcription with an original journal facsimile.','Extend review beyond the four named passages.'],parse(node['source_ids']),context='Selected passages: PDF pages 3, 4, 8, and 10 of the 2008 printout.',editorial_note='Prepared with AI assistance. Four scoped statements; no independent specialist review or complete original-text review claimed.')
profile.update(title=node['label'],last_researched=DATE,profile_status='evidence_deepened_research_pass',review_status='research_pass_needs_editor')
upsert(d['profiles'],[profile],'node_id');d[MARK]=dict(release=RELEASE,source_id=SID,claim_count=4,review_scope=P['source']['review_scope'],reader_url=ROUTE)
refresh_counts(d);d['meta'].update(release=RELEASE,generated=DATE,release_digest_url='https://transduction.systems'+ROUTE,node_count=len(d['nodes']),edge_count=len(d['edges']),source_count=len(d['sources']),profile_count=len(d['profiles']))
d['relational_depth']=calculate_relational_depth(d);d['relational_depth'].update(release=RELEASE,generated=DATE);d['graph_snapshot']=calculate(d)
metrics=graph_metrics(d);depth=d['relational_depth']['aggregate']
d['meta'].update(public_entry_count=metrics['public_entries'],described_entry_count=metrics['public_entries'],reader_connected_entry_count=depth['reader_connected_entries'],semantic_connected_entry_count=depth['semantic_connected_entries'],unconnected_entry_count=depth['connection_bands'].get('unconnected',0),semantic_gap_entry_count=metrics['public_entries']-depth['semantic_connected_entries'],public_link_source_count=sum(s.get('public_link_status')=='public_link' for s in d['sources']),no_public_link_source_count=sum(s.get('public_link_status')=='no_public_link' for s in d['sources']))
for band in ['rich','developing','thin']:d['meta'][band+'_entry_count']=depth['connection_bands'].get(band,0)
for key in ['reading_list_inventory','reading_list_coverage','core_systems_practice']:d[key]['release']=RELEASE
d['ai_observations'].update(release=RELEASE,generated=DATE,metrics=metrics);upsert(d['ai_observations']['observations'],make_ai_observations(metrics)['observations'],'id')
write(d);q=quality_result(d);q.update(release=RELEASE,generated=DATE)
for key in ['adversarial_review','doncaster_lineage_review']:q[key]=d[key]
for path in ['data/relationship-quality.json','docs/assets/relationship-quality.json']:(ROOT/path).write_text(json.dumps(q,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
write_relational_document(d)
catalogue=DOCS/'assets/early-cybernetics-bibliography.json';cat=json.loads(catalogue.read_text(encoding='utf-8'))
for row in cat['entries']:
    if row['id']=='wiener-06':row.update(review_status='selected_passages_reviewed',full_text_reviewed=False,primary_url=P['source']['access_url'],review_locator='Later transcription PDF pages 3, 4, 8, and 10; original journal pagination unverified',notes=[P['source']['integrity_note']])
catalogue.write_text(json.dumps(cat,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
E=lambda x:html.escape(str(x),quote=True)
body='<p>A historical source can help sharpen a present question without deciding it. This reading uses four passages from Warren Weaver’s <cite>Science and Complexity</cite> and keeps the source account separate from an organisational exercise.</p><section id="source-limits"><h2>Which text was checked?</h2><p>'+E(P['source']['representation'])+'</p><p>'+E(P['source']['review_scope'])+' '+E(P['source']['integrity_note'])+'</p><p><a href="'+E(P['source']['access_url'])+'">Open the inspected transcription</a>. The locators below are its PDF pages, not American Scientist page numbers. No source PDF has been republished.</p></section><section id="claims"><h2>Four located claims</h2>'
for c in P['claims']:
    edge='e29_'+c['id'].replace('-','_')
    body+='<article id="'+c['id']+'"><h3>'+E(c['target_label'])+'</h3><p>'+E(c['reader_statement'])+'</p><p class="meta">'+E(c['locator'])+'</p><p><a href="/#view=item&amp;id='+PUB+'">Weaver’s existing atlas entry</a> · <a href="/#view=map&amp;focus='+PUB+'&amp;layer=substantive&amp;depth=constellation&amp;edge='+edge+'">Inspect the graph neighbourhood</a> · <a href="/#view=item&amp;id='+c['target_id']+'">'+E(nodes[c['target_id']]['label'])+'</a></p><p class="meta">'+E(c['status'])+'. Graph relation: '+E(c['relation_type'].replace('_',' '))+'.</p></article>'
body+='</section><section id="application"><h2>Organisational application: what would you need to add?</h2><p>This is an original editorial exercise, not a claim that Weaver investigated this service or endorsed the proposed method.</p><p>A fictional housing team proposes to predict demand using a single mean arrival rate. Staff report coordinated surges after letters are issued, and repeat contacts after failed repairs. The sponsor also wants the model to decide who should receive a scarce appointment first.</p><ol><li>Specify the decision the prediction must support. What timing, grouping, and repeated contacts does the average conceal?</li><li>State a test under which the proposed model would be useful, and a pattern that would expose its limits. What additional data would discriminate between those possibilities?</li><li>Choose who must work together on this question and what each contributes. Explain which work can sensibly be done independently.</li><li>Separate a prediction about consequences from a judgement about fair access. Who has authority to make that judgement, and how can affected people challenge it?</li></ol><details><summary>Compare a possible response</summary><p>Track arrivals against the letter schedule and retain the link between a failed repair and a repeat contact. Compare the simple average with observed peaks before adopting a more elaborate model. Bring service knowledge and analytical skills together for the decisions that need both. A technically credible forecast still leaves the allocation criteria and legitimate authority to be settled. Neither a historical citation nor the model grants that authority.</p></details><p><a href="/systems-thinking/claim-lab/the-average-improved/">Practise the average and boundary check</a> · <a href="/systems-thinking/claim-lab/four-methods-one-answer/">Practise a method transition</a> · <a href="/systems-thinking/practice/critical-systems-heuristics/">Examine authority and affected people</a></p></section><p><a href="review.json">Download the source and claim record</a> · <a href="/corpora/early-cybernetics/">Return to the early cybernetics catalogue</a></p>'
css='body{margin:0;background:#faf8f2;color:#302b26;font:18px/1.65 Georgia,serif}main,nav,footer{max-width:62rem;margin:auto;padding:1.4rem}nav{display:flex;gap:1rem;flex-wrap:wrap;font:1rem/1.5 system-ui}a{color:#973d32;overflow-wrap:anywhere}a:focus-visible,summary:focus-visible{outline:3px solid #973d32;outline-offset:3px}h1{font-size:clamp(2.2rem,6vw,3.5rem);line-height:1.15}section,article{border-bottom:1px solid #d8d0c5;padding-bottom:1rem;margin-bottom:1.5rem}.meta{font:1rem/1.5 system-ui}summary{cursor:pointer;font-weight:bold}#openUpdates{position:fixed;bottom:0;right:0;width:44px;height:44px}#openUpdates:after{content:"";position:absolute;right:7px;bottom:7px;width:6px;height:6px;background:white;border-radius:50%;box-shadow:0 0 0 1px #777}@media(max-width:600px){main,nav,footer{padding:1rem}}'
dest=DOCS/'reading/weaver-complexity';dest.mkdir(parents=True,exist_ok=True)
(dest/'index.html').write_text('<!doctype html><html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Weaver: what the argument permits | The Necessary Tangle</title><link rel="canonical" href="https://transduction.systems'+ROUTE+'"><style>'+css+'</style></head><body><nav aria-label="Main"><a href="/">Atlas</a><a href="/reading-list.html">Reading</a><a href="/systems-thinking/claim-lab/">Test a claim</a></nav><main><p class="meta">Source release 0.29 · 4 October 2026</p><h1>Weaver: what the argument permits</h1>'+body+'</main><footer><p>Prepared with AI assistance. Curator: Benjamin P Taylor. Source-located statements remain open to editorial review. Organisational applications are labelled separately.</p></footer><a id="openUpdates" href="https://github.com/antlerboy/the-necessary-tangle/issues/2" aria-label="Open updates"></a></body></html>',encoding='utf-8')
(dest/'review.json').write_text(json.dumps(P,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
for route in ['reading-list.html','corpora/early-cybernetics/index.html','updates/index.html']:
    p=DOCS/route;t=p.read_text(encoding='utf-8');t=re.sub('<!-- '+MARK+' -->.*?<!-- /'+MARK+' -->','',t,flags=re.S);assert '</main>' in t
    t=t.replace('</main>','<!-- '+MARK+' --><section><h2>Read Weaver with the limits intact</h2><p><a href="'+ROUTE+'">Four source-located claims and a separate organisational exercise</a>. Selected passages in a later transcription; original journal pagination remains unchecked.</p></section><!-- /'+MARK+' --></main>',1);p.write_text(t,encoding='utf-8')
p=DOCS/'sitemap.xml';t=p.read_text(encoding='utf-8');url='https://transduction.systems'+ROUTE
if url not in t:p.write_text(t.replace('</urlset>','<url><loc>'+url+'</loc><lastmod>'+DATE+'</lastmod></url></urlset>'),encoding='utf-8')
p=DOCS/'index.html';t=p.read_text(encoding='utf-8');p.write_text(re.sub(r'assets/public-data.js\?v=[^"\s]+','assets/public-data.js?v=0.29',t),encoding='utf-8')
p=ROOT/'CITATION.cff';t=p.read_text(encoding='utf-8');t=re.sub(r'(?m)^version:.*$',"version: '0.29'",t);t=re.sub(r'(?m)^date-released:.*$',"date-released: '2026-10-04'",t);p.write_text(t,encoding='utf-8')
for name in ['TANGLE_STATE.md','NEXT_WORK.md']:
    p=ROOT/'documentation'/name;t=p.read_text(encoding='utf-8');heading='## Weaver source pass, 4 October 2026'
    if heading not in t:p.write_text(t+'\n\n'+heading+'\n\nRelease 0.29 adds four selected-passage statements using existing identities and relation types, one publication profile, and a source/application comparison. Transcription quality and actual PDF locators are explicit. Packet and acceptance checks: sources/weaver-2026-10-04/PACKET.md. No original-edition review, new lineage, or independent specialist review is claimed.\n',encoding='utf-8')
print('Applied Weaver source release 0.29: four located candidate statements; no new identities or relation types.')
