(() => {
  const $=id=>document.getElementById(id),esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const normalise=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  const names={authorship:'Author or presenter credit',identity:'Identity link',teaching_account:'Teaching account',text_mention:'Text mention',title_match:'Title match'};
  let records=[],filtered=[],page=0;const size=40,params=new URLSearchParams(location.search);
  const graph=id=>'/#view=map&layer=all&depth=constellation&focus='+encodeURIComponent(id);
  const atlas=id=>'/#view=item&id='+encodeURIComponent(id);
  function connections(item,limit=5){return (item.connections||[]).slice(0,limit).map(c=>'<li><a href="'+atlas(c.target)+'">'+esc(c.label)+'</a><span class="connection-kind">'+esc(names[c.kind]||c.kind)+' · '+esc(c.locator)+'</span></li>').join('');}
  function card(item){return '<article class="source-card"><h2><a href="'+esc(item.url)+'">'+esc(item.title)+'</a></h2><p class="meta">'+esc([item.collection,item.year,item.format].filter(Boolean).join(' · '))+'</p>'+(item.authors?.length?'<p class="meta">'+esc(item.authors.join(', '))+'</p>':'')+'<p>'+esc(item.summary)+'</p><p class="meta">'+esc(item.review)+'</p>'+(item.connections.length?'<ul class="connections">'+connections(item)+'</ul>':'<p class="meta">No concept connection recorded yet.</p>')+'<div class="actions"><a href="?item='+encodeURIComponent(item.id)+'">Source and connections'+(item.connections.length?' ('+item.connections.length+')':'')+'</a>'+(item.atlas_id?'<a href="'+atlas(item.atlas_id)+'">Atlas entry</a>':'')+'</div></article>';}
  function selected(id){const item=records.find(r=>r.id===id);if(!item)return;const detail=$('source-detail');detail.hidden=false;detail.innerHTML='<h2>'+esc(item.title)+'</h2><p>'+esc(item.summary)+'</p><p class="meta">'+esc(item.review)+'</p><p><a href="'+esc(item.url)+'">Open the source</a>'+(item.atlas_id?' · <a href="'+atlas(item.atlas_id)+'">Open its atlas entry</a> · <a href="'+graph(item.atlas_id)+'">Explore on the map</a>':'')+'</p>'+(item.connections.length?'<div class="source-map" aria-label="Source-to-concept connections"><div class="map-origin">'+esc(item.title)+'</div><ul class="map-targets connections">'+connections(item,Infinity)+'</ul></div>':'<p>No concept connection has been recorded. This remains a catalogue entry.</p>')+'<p class="meta">Connections show their evidence level and locator. Read the source before inferring agreement, influence, or conceptual dependence.</p><p><a href="./">Return to the full register</a></p>';}
  function render(){const total=Math.max(1,Math.ceil(filtered.length/size));page=Math.min(page,total-1);$('results').innerHTML=filtered.slice(page*size,(page+1)*size).map(card).join('');$('result-count').textContent=filtered.length?`${filtered.length.toLocaleString()} of ${records.length.toLocaleString()} sources match. Showing ${page*size+1}–${Math.min((page+1)*size,filtered.length)}.`:'No sources match. Try fewer words or reset the search.';$('page-count').textContent=`Page ${page+1} of ${total}`;$('previous').disabled=page===0;$('next').disabled=page>=total-1;$('pagination').hidden=!filtered.length;}
  function filter(){const words=normalise($('library-query').value).trim().split(/\s+/).filter(Boolean),collection=$('library-collection').value,concept=$('library-concept').value,evidence=$('library-evidence').value;filtered=records.filter(r=>(!collection||r.collection===collection)&&(!concept||r.connections.some(c=>c.target===concept))&&(!evidence||(evidence==='none'?!r.connections.length:r.connections.some(c=>c.kind===evidence)))&&words.every(w=>r.search.includes(w)));page=0;render();}
  $('search').addEventListener('submit',e=>{e.preventDefault();filter();});$('library-query').addEventListener('input',filter);for(const id of ['library-collection','library-concept','library-evidence'])$(id).addEventListener('change',filter);$('library-reset').addEventListener('click',()=>{for(const id of ['library-query','library-collection','library-concept','library-evidence'])$(id).value='';filter();$('library-query').focus();});$('previous').addEventListener('click',()=>{page--;render();$('result-count').scrollIntoView({block:'start'});});$('next').addEventListener('click',()=>{page++;render();$('result-count').scrollIntoView({block:'start'});});
  fetch('catalogue.json').then(r=>{if(!r.ok)throw Error('Source register unavailable');return r.json();}).then(data=>{records=data.records.map(r=>({...r,connections:r.connections||[],search:normalise([r.title,r.summary,(r.authors||[]).join(' '),...(r.connections||[]).map(c=>c.label)].join(' '))}));for(const value of [...new Set(records.map(r=>r.collection))].sort())$('library-collection').add(new Option(value,value));const concepts=new Map();records.forEach(r=>r.connections.forEach(c=>concepts.set(c.target,c.label)));for(const [id,label] of [...concepts].sort((a,b)=>a[1].localeCompare(b[1])))$('library-concept').add(new Option(label,id));$('coverage-summary').textContent=`${records.length.toLocaleString()} source records, including ${data.counts.antlerboy_manifest_resources} public-library resources and ${data.counts.large_group_entries} large-group entries. Eight teaching-source records now link to their public PDFs.`;$('authorship').textContent=data.authorship;$('research-status').textContent=`Research collection: ${data.research_collection.indexed_files.toLocaleString()} indexed files across four requested folders. ${data.research_collection.status}`;$('library-query').value=params.get('q')||'';if(params.get('collection'))$('library-collection').value=params.get('collection');if(params.get('concept'))$('library-concept').value=params.get('concept');filter();if(params.get('item'))selected(params.get('item'));}).catch(()=>{$('load-error').hidden=false;$('coverage-summary').textContent='Source register unavailable';$('pagination').hidden=true;});
})();
